/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgSlugRouteRouteImport } from './routes/$orgSlug/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CreateRouteImport } from './routes/create'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OrgSlugIndexRouteImport } from './routes/$orgSlug/index'
import { Route as OrgSlugDashboardRouteImport } from './routes/$orgSlug/dashboard'
import { Route as OrgSlugFilesRouteImport } from './routes/$orgSlug/files'
import { Route as OrgSlugOnboardingRouteImport } from './routes/$orgSlug/onboarding'
import { Route as OrgSlugPartiesRouteRouteImport } from './routes/$orgSlug/parties/route'
import { Route as OrgSlugReceiptsRouteRouteImport } from './routes/$orgSlug/receipts/route'
import { Route as OrgSlugSettingsRouteRouteImport } from './routes/$orgSlug/settings/route'
import { Route as ChangelogIndexRouteImport } from './routes/changelog.index'
import { Route as ChangelogSlugRouteImport } from './routes/changelog.$slug'
import { Route as OrgSlugBillingIndexRouteImport } from './routes/$orgSlug/billing/index'
import { Route as OrgSlugCustomersIndexRouteImport } from './routes/$orgSlug/customers/index'
import { Route as OrgSlugCustomersCustomerIdRouteImport } from './routes/$orgSlug/customers/$customerId'
import { Route as OrgSlugOpdIndexRouteImport } from './routes/$orgSlug/opd/index'
import { Route as OrgSlugOpdAppointmentIdRouteRouteImport } from './routes/$orgSlug/opd/$appointmentId/route'
import { Route as OrgSlugOpdNewRouteImport } from './routes/$orgSlug/opd/new'
import { Route as OrgSlugPartiesPartyIdRouteImport } from './routes/$orgSlug/parties_.$partyId'
import { Route as OrgSlugReceiptsReceiptIdRouteImport } from './routes/$orgSlug/receipts/$receiptId'
import { Route as OrgSlugReportsIndexRouteImport } from './routes/$orgSlug/reports/index'
import { Route as OrgSlugReportsBalanceSheetRouteImport } from './routes/$orgSlug/reports/balance-sheet'
import { Route as OrgSlugReportsDailyCollectionsRouteImport } from './routes/$orgSlug/reports/daily-collections'
import { Route as OrgSlugReportsGstRouteImport } from './routes/$orgSlug/reports/gst'
import { Route as OrgSlugReportsOpdRegisterRouteImport } from './routes/$orgSlug/reports/opd-register'
import { Route as OrgSlugReportsTrialBalanceRouteImport } from './routes/$orgSlug/reports/trial-balance'
import { Route as OrgSlugSettingsIndexRouteImport } from './routes/$orgSlug/settings/index'
import { Route as OrgSlugSettingsAuditRouteImport } from './routes/$orgSlug/settings/audit'
import { Route as OrgSlugSettingsItemsRouteImport } from './routes/$orgSlug/settings/items'
import { Route as OrgSlugSettingsMembersRouteImport } from './routes/$orgSlug/settings/members'
import { Route as OrgSlugSettingsOrganizationRouteImport } from './routes/$orgSlug/settings/organization'
import { Route as OrgSlugSettingsPayersRouteImport } from './routes/$orgSlug/settings/payers'
import { Route as OrgSlugSettingsStaffRouteImport } from './routes/$orgSlug/settings/staff'
import { Route as OrgSlugBillingInvoicesInvoiceIdRouteImport } from './routes/$orgSlug/billing/invoices.$invoiceId'
import { Route as OrgSlugOpdAppointmentIdIndexRouteImport } from './routes/$orgSlug/opd/$appointmentId/index'
import { Route as OrgSlugOpdAppointmentIdBillingRouteImport } from './routes/$orgSlug/opd/$appointmentId/billing'
import { Route as OrgSlugPartiesPartyIdIndexRouteImport } from './routes/$orgSlug/parties_.$partyId.index'
import { Route as OrgSlugPartiesPartyIdLedgerRouteImport } from './routes/$orgSlug/parties_.$partyId.ledger'
import { Route as OrgSlugPartiesPartyIdReceiptsRouteImport } from './routes/$orgSlug/parties_.$partyId.receipts'
import { Route as ApiOrgSlugReceiptsReceiptIdPdfRouteImport } from './routes/api.$orgSlug.receipts.$receiptId.pdf'
import { Route as OrgSlugBillingInvoicesInvoiceIdCreditNoteCreditNoteIdRouteImport } from './routes/$orgSlug/billing/invoices.$invoiceId_.credit-note.$creditNoteId'
import { Route as OrgSlugBillingInvoicesInvoiceIdReceiptPaymentIdRouteImport } from './routes/$orgSlug/billing/invoices.$invoiceId_.receipt.$paymentId'
import { Route as OrgSlugBillingInvoicesInvoiceIdRefundRefundIdRouteImport } from './routes/$orgSlug/billing/invoices.$invoiceId_.refund.$refundId'
import { Route as ApiOrgSlugBillingInvoicesInvoiceIdPdfRouteImport } from './routes/api.$orgSlug.billing.invoices.$invoiceId.pdf'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugRouteRoute = OrgSlugRouteRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugIndexRoute = OrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugDashboardRoute = OrgSlugDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugFilesRoute = OrgSlugFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugOnboardingRoute = OrgSlugOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugPartiesRouteRoute = OrgSlugPartiesRouteRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugReceiptsRouteRoute = OrgSlugReceiptsRouteRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugSettingsRouteRoute = OrgSlugSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const ChangelogIndexRoute = ChangelogIndexRouteImport.update({
  id: '/changelog/',
  path: '/changelog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogSlugRoute = ChangelogSlugRouteImport.update({
  id: '/changelog/$slug',
  path: '/changelog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugBillingIndexRoute = OrgSlugBillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugCustomersIndexRoute = OrgSlugCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugCustomersCustomerIdRoute =
  OrgSlugCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => OrgSlugRouteRoute,
  } as any)
const OrgSlugOpdIndexRoute = OrgSlugOpdIndexRouteImport.update({
  id: '/opd/',
  path: '/opd/',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugOpdAppointmentIdRouteRoute =
  OrgSlugOpdAppointmentIdRouteRouteImport.update({
    id: '/opd/$appointmentId',
    path: '/opd/$appointmentId',
    getParentRoute: () => OrgSlugRouteRoute,
  } as any)
const OrgSlugOpdNewRoute = OrgSlugOpdNewRouteImport.update({
  id: '/opd/new',
  path: '/opd/new',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugPartiesPartyIdRoute = OrgSlugPartiesPartyIdRouteImport.update({
  id: '/parties_/$partyId',
  path: '/parties/$partyId',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugReceiptsReceiptIdRoute =
  OrgSlugReceiptsReceiptIdRouteImport.update({
    id: '/$receiptId',
    path: '/$receiptId',
    getParentRoute: () => OrgSlugReceiptsRouteRoute,
  } as any)
const OrgSlugReportsIndexRoute = OrgSlugReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugReportsBalanceSheetRoute =
  OrgSlugReportsBalanceSheetRouteImport.update({
    id: '/reports/balance-sheet',
    path: '/reports/balance-sheet',
    getParentRoute: () => OrgSlugRouteRoute,
  } as any)
const OrgSlugReportsDailyCollectionsRoute =
  OrgSlugReportsDailyCollectionsRouteImport.update({
    id: '/reports/daily-collections',
    path: '/reports/daily-collections',
    getParentRoute: () => OrgSlugRouteRoute,
  } as any)
const OrgSlugReportsGstRoute = OrgSlugReportsGstRouteImport.update({
  id: '/reports/gst',
  path: '/reports/gst',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugReportsOpdRegisterRoute =
  OrgSlugReportsOpdRegisterRouteImport.update({
    id: '/reports/opd-register',
    path: '/reports/opd-register',
    getParentRoute: () => OrgSlugRouteRoute,
  } as any)
const OrgSlugReportsTrialBalanceRoute =
  OrgSlugReportsTrialBalanceRouteImport.update({
    id: '/reports/trial-balance',
    path: '/reports/trial-balance',
    getParentRoute: () => OrgSlugRouteRoute,
  } as any)
const OrgSlugSettingsIndexRoute = OrgSlugSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgSlugSettingsRouteRoute,
} as any)
const OrgSlugSettingsAuditRoute = OrgSlugSettingsAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => OrgSlugSettingsRouteRoute,
} as any)
const OrgSlugSettingsItemsRoute = OrgSlugSettingsItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => OrgSlugSettingsRouteRoute,
} as any)
const OrgSlugSettingsMembersRoute = OrgSlugSettingsMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => OrgSlugSettingsRouteRoute,
} as any)
const OrgSlugSettingsOrganizationRoute =
  OrgSlugSettingsOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => OrgSlugSettingsRouteRoute,
  } as any)
const OrgSlugSettingsPayersRoute = OrgSlugSettingsPayersRouteImport.update({
  id: '/payers',
  path: '/payers',
  getParentRoute: () => OrgSlugSettingsRouteRoute,
} as any)
const OrgSlugSettingsStaffRoute = OrgSlugSettingsStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => OrgSlugSettingsRouteRoute,
} as any)
const OrgSlugBillingInvoicesInvoiceIdRoute =
  OrgSlugBillingInvoicesInvoiceIdRouteImport.update({
    id: '/billing/invoices/$invoiceId',
    path: '/billing/invoices/$invoiceId',
    getParentRoute: () => OrgSlugRouteRoute,
  } as any)
const OrgSlugOpdAppointmentIdIndexRoute =
  OrgSlugOpdAppointmentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrgSlugOpdAppointmentIdRouteRoute,
  } as any)
const OrgSlugOpdAppointmentIdBillingRoute =
  OrgSlugOpdAppointmentIdBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => OrgSlugOpdAppointmentIdRouteRoute,
  } as any)
const OrgSlugPartiesPartyIdIndexRoute =
  OrgSlugPartiesPartyIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrgSlugPartiesPartyIdRoute,
  } as any)
const OrgSlugPartiesPartyIdLedgerRoute =
  OrgSlugPartiesPartyIdLedgerRouteImport.update({
    id: '/ledger',
    path: '/ledger',
    getParentRoute: () => OrgSlugPartiesPartyIdRoute,
  } as any)
const OrgSlugPartiesPartyIdReceiptsRoute =
  OrgSlugPartiesPartyIdReceiptsRouteImport.update({
    id: '/receipts',
    path: '/receipts',
    getParentRoute: () => OrgSlugPartiesPartyIdRoute,
  } as any)
const ApiOrgSlugReceiptsReceiptIdPdfRoute =
  ApiOrgSlugReceiptsReceiptIdPdfRouteImport.update({
    id: '/api/$orgSlug/receipts/$receiptId/pdf',
    path: '/api/$orgSlug/receipts/$receiptId/pdf',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgSlugBillingInvoicesInvoiceIdCreditNoteCreditNoteIdRoute =
  OrgSlugBillingInvoicesInvoiceIdCreditNoteCreditNoteIdRouteImport.update({
    id: '/billing/invoices/$invoiceId_/credit-note/$creditNoteId',
    path: '/billing/invoices/$invoiceId/credit-note/$creditNoteId',
    getParentRoute: () => OrgSlugRouteRoute,
  } as any)
const OrgSlugBillingInvoicesInvoiceIdReceiptPaymentIdRoute =
  OrgSlugBillingInvoicesInvoiceIdReceiptPaymentIdRouteImport.update({
    id: '/billing/invoices/$invoiceId_/receipt/$paymentId',
    path: '/billing/invoices/$invoiceId/receipt/$paymentId',
    getParentRoute: () => OrgSlugRouteRoute,
  } as any)
const OrgSlugBillingInvoicesInvoiceIdRefundRefundIdRoute =
  OrgSlugBillingInvoicesInvoiceIdRefundRefundIdRouteImport.update({
    id: '/billing/invoices/$invoiceId_/refund/$refundId',
    path: '/billing/invoices/$invoiceId/refund/$refundId',
    getParentRoute: () => OrgSlugRouteRoute,
  } as any)
const ApiOrgSlugBillingInvoicesInvoiceIdPdfRoute =
  ApiOrgSlugBillingInvoicesInvoiceIdPdfRouteImport.update({
    id: '/api/$orgSlug/billing/invoices/$invoiceId/pdf',
    path: '/api/$orgSlug/billing/invoices/$invoiceId/pdf',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/billing': typeof BillingRoute
  '/contact': typeof ContactRoute
  '/create': typeof CreateRoute
  '/customers': typeof CustomersRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$orgSlug/parties': typeof OrgSlugPartiesRouteRoute
  '/$orgSlug/receipts': typeof OrgSlugReceiptsRouteRouteWithChildren
  '/$orgSlug/settings': typeof OrgSlugSettingsRouteRouteWithChildren
  '/$orgSlug/dashboard': typeof OrgSlugDashboardRoute
  '/$orgSlug/files': typeof OrgSlugFilesRoute
  '/$orgSlug/onboarding': typeof OrgSlugOnboardingRoute
  '/changelog/$slug': typeof ChangelogSlugRoute
  '/$orgSlug/': typeof OrgSlugIndexRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/$orgSlug/opd/$appointmentId': typeof OrgSlugOpdAppointmentIdRouteRouteWithChildren
  '/$orgSlug/customers/$customerId': typeof OrgSlugCustomersCustomerIdRoute
  '/$orgSlug/opd/new': typeof OrgSlugOpdNewRoute
  '/$orgSlug/parties/$partyId': typeof OrgSlugPartiesPartyIdRouteWithChildren
  '/$orgSlug/receipts/$receiptId': typeof OrgSlugReceiptsReceiptIdRoute
  '/$orgSlug/reports/balance-sheet': typeof OrgSlugReportsBalanceSheetRoute
  '/$orgSlug/reports/daily-collections': typeof OrgSlugReportsDailyCollectionsRoute
  '/$orgSlug/reports/gst': typeof OrgSlugReportsGstRoute
  '/$orgSlug/reports/opd-register': typeof OrgSlugReportsOpdRegisterRoute
  '/$orgSlug/reports/trial-balance': typeof OrgSlugReportsTrialBalanceRoute
  '/$orgSlug/settings/audit': typeof OrgSlugSettingsAuditRoute
  '/$orgSlug/settings/items': typeof OrgSlugSettingsItemsRoute
  '/$orgSlug/settings/members': typeof OrgSlugSettingsMembersRoute
  '/$orgSlug/settings/organization': typeof OrgSlugSettingsOrganizationRoute
  '/$orgSlug/settings/payers': typeof OrgSlugSettingsPayersRoute
  '/$orgSlug/settings/staff': typeof OrgSlugSettingsStaffRoute
  '/$orgSlug/billing/': typeof OrgSlugBillingIndexRoute
  '/$orgSlug/customers/': typeof OrgSlugCustomersIndexRoute
  '/$orgSlug/opd/': typeof OrgSlugOpdIndexRoute
  '/$orgSlug/reports/': typeof OrgSlugReportsIndexRoute
  '/$orgSlug/settings/': typeof OrgSlugSettingsIndexRoute
  '/$orgSlug/billing/invoices/$invoiceId': typeof OrgSlugBillingInvoicesInvoiceIdRoute
  '/$orgSlug/opd/$appointmentId/billing': typeof OrgSlugOpdAppointmentIdBillingRoute
  '/$orgSlug/parties/$partyId/ledger': typeof OrgSlugPartiesPartyIdLedgerRoute
  '/$orgSlug/parties/$partyId/receipts': typeof OrgSlugPartiesPartyIdReceiptsRoute
  '/$orgSlug/opd/$appointmentId/': typeof OrgSlugOpdAppointmentIdIndexRoute
  '/$orgSlug/parties/$partyId/': typeof OrgSlugPartiesPartyIdIndexRoute
  '/api/$orgSlug/receipts/$receiptId/pdf': typeof ApiOrgSlugReceiptsReceiptIdPdfRoute
  '/$orgSlug/billing/invoices/$invoiceId/credit-note/$creditNoteId': typeof OrgSlugBillingInvoicesInvoiceIdCreditNoteCreditNoteIdRoute
  '/$orgSlug/billing/invoices/$invoiceId/receipt/$paymentId': typeof OrgSlugBillingInvoicesInvoiceIdReceiptPaymentIdRoute
  '/$orgSlug/billing/invoices/$invoiceId/refund/$refundId': typeof OrgSlugBillingInvoicesInvoiceIdRefundRefundIdRoute
  '/api/$orgSlug/billing/invoices/$invoiceId/pdf': typeof ApiOrgSlugBillingInvoicesInvoiceIdPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/billing': typeof BillingRoute
  '/contact': typeof ContactRoute
  '/create': typeof CreateRoute
  '/customers': typeof CustomersRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$orgSlug/parties': typeof OrgSlugPartiesRouteRoute
  '/$orgSlug/receipts': typeof OrgSlugReceiptsRouteRouteWithChildren
  '/$orgSlug/dashboard': typeof OrgSlugDashboardRoute
  '/$orgSlug/files': typeof OrgSlugFilesRoute
  '/$orgSlug/onboarding': typeof OrgSlugOnboardingRoute
  '/changelog/$slug': typeof ChangelogSlugRoute
  '/$orgSlug': typeof OrgSlugIndexRoute
  '/changelog': typeof ChangelogIndexRoute
  '/$orgSlug/customers/$customerId': typeof OrgSlugCustomersCustomerIdRoute
  '/$orgSlug/opd/new': typeof OrgSlugOpdNewRoute
  '/$orgSlug/receipts/$receiptId': typeof OrgSlugReceiptsReceiptIdRoute
  '/$orgSlug/reports/balance-sheet': typeof OrgSlugReportsBalanceSheetRoute
  '/$orgSlug/reports/daily-collections': typeof OrgSlugReportsDailyCollectionsRoute
  '/$orgSlug/reports/gst': typeof OrgSlugReportsGstRoute
  '/$orgSlug/reports/opd-register': typeof OrgSlugReportsOpdRegisterRoute
  '/$orgSlug/reports/trial-balance': typeof OrgSlugReportsTrialBalanceRoute
  '/$orgSlug/settings/audit': typeof OrgSlugSettingsAuditRoute
  '/$orgSlug/settings/items': typeof OrgSlugSettingsItemsRoute
  '/$orgSlug/settings/members': typeof OrgSlugSettingsMembersRoute
  '/$orgSlug/settings/organization': typeof OrgSlugSettingsOrganizationRoute
  '/$orgSlug/settings/payers': typeof OrgSlugSettingsPayersRoute
  '/$orgSlug/settings/staff': typeof OrgSlugSettingsStaffRoute
  '/$orgSlug/billing': typeof OrgSlugBillingIndexRoute
  '/$orgSlug/customers': typeof OrgSlugCustomersIndexRoute
  '/$orgSlug/opd': typeof OrgSlugOpdIndexRoute
  '/$orgSlug/reports': typeof OrgSlugReportsIndexRoute
  '/$orgSlug/settings': typeof OrgSlugSettingsIndexRoute
  '/$orgSlug/billing/invoices/$invoiceId': typeof OrgSlugBillingInvoicesInvoiceIdRoute
  '/$orgSlug/opd/$appointmentId/billing': typeof OrgSlugOpdAppointmentIdBillingRoute
  '/$orgSlug/parties/$partyId/ledger': typeof OrgSlugPartiesPartyIdLedgerRoute
  '/$orgSlug/parties/$partyId/receipts': typeof OrgSlugPartiesPartyIdReceiptsRoute
  '/$orgSlug/opd/$appointmentId': typeof OrgSlugOpdAppointmentIdIndexRoute
  '/$orgSlug/parties/$partyId': typeof OrgSlugPartiesPartyIdIndexRoute
  '/api/$orgSlug/receipts/$receiptId/pdf': typeof ApiOrgSlugReceiptsReceiptIdPdfRoute
  '/$orgSlug/billing/invoices/$invoiceId/credit-note/$creditNoteId': typeof OrgSlugBillingInvoicesInvoiceIdCreditNoteCreditNoteIdRoute
  '/$orgSlug/billing/invoices/$invoiceId/receipt/$paymentId': typeof OrgSlugBillingInvoicesInvoiceIdReceiptPaymentIdRoute
  '/$orgSlug/billing/invoices/$invoiceId/refund/$refundId': typeof OrgSlugBillingInvoicesInvoiceIdRefundRefundIdRoute
  '/api/$orgSlug/billing/invoices/$invoiceId/pdf': typeof ApiOrgSlugBillingInvoicesInvoiceIdPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/billing': typeof BillingRoute
  '/contact': typeof ContactRoute
  '/create': typeof CreateRoute
  '/customers': typeof CustomersRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$orgSlug/parties': typeof OrgSlugPartiesRouteRoute
  '/$orgSlug/receipts': typeof OrgSlugReceiptsRouteRouteWithChildren
  '/$orgSlug/settings': typeof OrgSlugSettingsRouteRouteWithChildren
  '/$orgSlug/dashboard': typeof OrgSlugDashboardRoute
  '/$orgSlug/files': typeof OrgSlugFilesRoute
  '/$orgSlug/onboarding': typeof OrgSlugOnboardingRoute
  '/changelog/$slug': typeof ChangelogSlugRoute
  '/$orgSlug/': typeof OrgSlugIndexRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/$orgSlug/opd/$appointmentId': typeof OrgSlugOpdAppointmentIdRouteRouteWithChildren
  '/$orgSlug/customers/$customerId': typeof OrgSlugCustomersCustomerIdRoute
  '/$orgSlug/opd/new': typeof OrgSlugOpdNewRoute
  '/$orgSlug/parties_/$partyId': typeof OrgSlugPartiesPartyIdRouteWithChildren
  '/$orgSlug/receipts/$receiptId': typeof OrgSlugReceiptsReceiptIdRoute
  '/$orgSlug/reports/balance-sheet': typeof OrgSlugReportsBalanceSheetRoute
  '/$orgSlug/reports/daily-collections': typeof OrgSlugReportsDailyCollectionsRoute
  '/$orgSlug/reports/gst': typeof OrgSlugReportsGstRoute
  '/$orgSlug/reports/opd-register': typeof OrgSlugReportsOpdRegisterRoute
  '/$orgSlug/reports/trial-balance': typeof OrgSlugReportsTrialBalanceRoute
  '/$orgSlug/settings/audit': typeof OrgSlugSettingsAuditRoute
  '/$orgSlug/settings/items': typeof OrgSlugSettingsItemsRoute
  '/$orgSlug/settings/members': typeof OrgSlugSettingsMembersRoute
  '/$orgSlug/settings/organization': typeof OrgSlugSettingsOrganizationRoute
  '/$orgSlug/settings/payers': typeof OrgSlugSettingsPayersRoute
  '/$orgSlug/settings/staff': typeof OrgSlugSettingsStaffRoute
  '/$orgSlug/billing/': typeof OrgSlugBillingIndexRoute
  '/$orgSlug/customers/': typeof OrgSlugCustomersIndexRoute
  '/$orgSlug/opd/': typeof OrgSlugOpdIndexRoute
  '/$orgSlug/reports/': typeof OrgSlugReportsIndexRoute
  '/$orgSlug/settings/': typeof OrgSlugSettingsIndexRoute
  '/$orgSlug/billing/invoices/$invoiceId': typeof OrgSlugBillingInvoicesInvoiceIdRoute
  '/$orgSlug/opd/$appointmentId/billing': typeof OrgSlugOpdAppointmentIdBillingRoute
  '/$orgSlug/parties_/$partyId/ledger': typeof OrgSlugPartiesPartyIdLedgerRoute
  '/$orgSlug/parties_/$partyId/receipts': typeof OrgSlugPartiesPartyIdReceiptsRoute
  '/$orgSlug/opd/$appointmentId/': typeof OrgSlugOpdAppointmentIdIndexRoute
  '/$orgSlug/parties_/$partyId/': typeof OrgSlugPartiesPartyIdIndexRoute
  '/api/$orgSlug/receipts/$receiptId/pdf': typeof ApiOrgSlugReceiptsReceiptIdPdfRoute
  '/$orgSlug/billing/invoices/$invoiceId_/credit-note/$creditNoteId': typeof OrgSlugBillingInvoicesInvoiceIdCreditNoteCreditNoteIdRoute
  '/$orgSlug/billing/invoices/$invoiceId_/receipt/$paymentId': typeof OrgSlugBillingInvoicesInvoiceIdReceiptPaymentIdRoute
  '/$orgSlug/billing/invoices/$invoiceId_/refund/$refundId': typeof OrgSlugBillingInvoicesInvoiceIdRefundRefundIdRoute
  '/api/$orgSlug/billing/invoices/$invoiceId/pdf': typeof ApiOrgSlugBillingInvoicesInvoiceIdPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$orgSlug'
    | '/about'
    | '/billing'
    | '/contact'
    | '/create'
    | '/customers'
    | '/join'
    | '/login'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$orgSlug/parties'
    | '/$orgSlug/receipts'
    | '/$orgSlug/settings'
    | '/$orgSlug/dashboard'
    | '/$orgSlug/files'
    | '/$orgSlug/onboarding'
    | '/changelog/$slug'
    | '/$orgSlug/'
    | '/changelog/'
    | '/$orgSlug/opd/$appointmentId'
    | '/$orgSlug/customers/$customerId'
    | '/$orgSlug/opd/new'
    | '/$orgSlug/parties/$partyId'
    | '/$orgSlug/receipts/$receiptId'
    | '/$orgSlug/reports/balance-sheet'
    | '/$orgSlug/reports/daily-collections'
    | '/$orgSlug/reports/gst'
    | '/$orgSlug/reports/opd-register'
    | '/$orgSlug/reports/trial-balance'
    | '/$orgSlug/settings/audit'
    | '/$orgSlug/settings/items'
    | '/$orgSlug/settings/members'
    | '/$orgSlug/settings/organization'
    | '/$orgSlug/settings/payers'
    | '/$orgSlug/settings/staff'
    | '/$orgSlug/billing/'
    | '/$orgSlug/customers/'
    | '/$orgSlug/opd/'
    | '/$orgSlug/reports/'
    | '/$orgSlug/settings/'
    | '/$orgSlug/billing/invoices/$invoiceId'
    | '/$orgSlug/opd/$appointmentId/billing'
    | '/$orgSlug/parties/$partyId/ledger'
    | '/$orgSlug/parties/$partyId/receipts'
    | '/$orgSlug/opd/$appointmentId/'
    | '/$orgSlug/parties/$partyId/'
    | '/api/$orgSlug/receipts/$receiptId/pdf'
    | '/$orgSlug/billing/invoices/$invoiceId/credit-note/$creditNoteId'
    | '/$orgSlug/billing/invoices/$invoiceId/receipt/$paymentId'
    | '/$orgSlug/billing/invoices/$invoiceId/refund/$refundId'
    | '/api/$orgSlug/billing/invoices/$invoiceId/pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/billing'
    | '/contact'
    | '/create'
    | '/customers'
    | '/join'
    | '/login'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$orgSlug/parties'
    | '/$orgSlug/receipts'
    | '/$orgSlug/dashboard'
    | '/$orgSlug/files'
    | '/$orgSlug/onboarding'
    | '/changelog/$slug'
    | '/$orgSlug'
    | '/changelog'
    | '/$orgSlug/customers/$customerId'
    | '/$orgSlug/opd/new'
    | '/$orgSlug/receipts/$receiptId'
    | '/$orgSlug/reports/balance-sheet'
    | '/$orgSlug/reports/daily-collections'
    | '/$orgSlug/reports/gst'
    | '/$orgSlug/reports/opd-register'
    | '/$orgSlug/reports/trial-balance'
    | '/$orgSlug/settings/audit'
    | '/$orgSlug/settings/items'
    | '/$orgSlug/settings/members'
    | '/$orgSlug/settings/organization'
    | '/$orgSlug/settings/payers'
    | '/$orgSlug/settings/staff'
    | '/$orgSlug/billing'
    | '/$orgSlug/customers'
    | '/$orgSlug/opd'
    | '/$orgSlug/reports'
    | '/$orgSlug/settings'
    | '/$orgSlug/billing/invoices/$invoiceId'
    | '/$orgSlug/opd/$appointmentId/billing'
    | '/$orgSlug/parties/$partyId/ledger'
    | '/$orgSlug/parties/$partyId/receipts'
    | '/$orgSlug/opd/$appointmentId'
    | '/$orgSlug/parties/$partyId'
    | '/api/$orgSlug/receipts/$receiptId/pdf'
    | '/$orgSlug/billing/invoices/$invoiceId/credit-note/$creditNoteId'
    | '/$orgSlug/billing/invoices/$invoiceId/receipt/$paymentId'
    | '/$orgSlug/billing/invoices/$invoiceId/refund/$refundId'
    | '/api/$orgSlug/billing/invoices/$invoiceId/pdf'
  id:
    | '__root__'
    | '/'
    | '/$orgSlug'
    | '/about'
    | '/billing'
    | '/contact'
    | '/create'
    | '/customers'
    | '/join'
    | '/login'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$orgSlug/parties'
    | '/$orgSlug/receipts'
    | '/$orgSlug/settings'
    | '/$orgSlug/dashboard'
    | '/$orgSlug/files'
    | '/$orgSlug/onboarding'
    | '/changelog/$slug'
    | '/$orgSlug/'
    | '/changelog/'
    | '/$orgSlug/opd/$appointmentId'
    | '/$orgSlug/customers/$customerId'
    | '/$orgSlug/opd/new'
    | '/$orgSlug/parties_/$partyId'
    | '/$orgSlug/receipts/$receiptId'
    | '/$orgSlug/reports/balance-sheet'
    | '/$orgSlug/reports/daily-collections'
    | '/$orgSlug/reports/gst'
    | '/$orgSlug/reports/opd-register'
    | '/$orgSlug/reports/trial-balance'
    | '/$orgSlug/settings/audit'
    | '/$orgSlug/settings/items'
    | '/$orgSlug/settings/members'
    | '/$orgSlug/settings/organization'
    | '/$orgSlug/settings/payers'
    | '/$orgSlug/settings/staff'
    | '/$orgSlug/billing/'
    | '/$orgSlug/customers/'
    | '/$orgSlug/opd/'
    | '/$orgSlug/reports/'
    | '/$orgSlug/settings/'
    | '/$orgSlug/billing/invoices/$invoiceId'
    | '/$orgSlug/opd/$appointmentId/billing'
    | '/$orgSlug/parties_/$partyId/ledger'
    | '/$orgSlug/parties_/$partyId/receipts'
    | '/$orgSlug/opd/$appointmentId/'
    | '/$orgSlug/parties_/$partyId/'
    | '/api/$orgSlug/receipts/$receiptId/pdf'
    | '/$orgSlug/billing/invoices/$invoiceId_/credit-note/$creditNoteId'
    | '/$orgSlug/billing/invoices/$invoiceId_/receipt/$paymentId'
    | '/$orgSlug/billing/invoices/$invoiceId_/refund/$refundId'
    | '/api/$orgSlug/billing/invoices/$invoiceId/pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrgSlugRouteRoute: typeof OrgSlugRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  BillingRoute: typeof BillingRoute
  ContactRoute: typeof ContactRoute
  CreateRoute: typeof CreateRoute
  CustomersRoute: typeof CustomersRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ChangelogSlugRoute: typeof ChangelogSlugRoute
  ChangelogIndexRoute: typeof ChangelogIndexRoute
  ApiOrgSlugReceiptsReceiptIdPdfRoute: typeof ApiOrgSlugReceiptsReceiptIdPdfRoute
  ApiOrgSlugBillingInvoicesInvoiceIdPdfRoute: typeof ApiOrgSlugBillingInvoicesInvoiceIdPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug': {
      id: '/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof OrgSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/': {
      id: '/$orgSlug/'
      path: '/'
      fullPath: '/$orgSlug/'
      preLoaderRoute: typeof OrgSlugIndexRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/dashboard': {
      id: '/$orgSlug/dashboard'
      path: '/dashboard'
      fullPath: '/$orgSlug/dashboard'
      preLoaderRoute: typeof OrgSlugDashboardRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/files': {
      id: '/$orgSlug/files'
      path: '/files'
      fullPath: '/$orgSlug/files'
      preLoaderRoute: typeof OrgSlugFilesRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/onboarding': {
      id: '/$orgSlug/onboarding'
      path: '/onboarding'
      fullPath: '/$orgSlug/onboarding'
      preLoaderRoute: typeof OrgSlugOnboardingRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/parties': {
      id: '/$orgSlug/parties'
      path: '/parties'
      fullPath: '/$orgSlug/parties'
      preLoaderRoute: typeof OrgSlugPartiesRouteRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/receipts': {
      id: '/$orgSlug/receipts'
      path: '/receipts'
      fullPath: '/$orgSlug/receipts'
      preLoaderRoute: typeof OrgSlugReceiptsRouteRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/settings': {
      id: '/$orgSlug/settings'
      path: '/settings'
      fullPath: '/$orgSlug/settings'
      preLoaderRoute: typeof OrgSlugSettingsRouteRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/changelog/': {
      id: '/changelog/'
      path: '/changelog'
      fullPath: '/changelog/'
      preLoaderRoute: typeof ChangelogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog/$slug': {
      id: '/changelog/$slug'
      path: '/changelog/$slug'
      fullPath: '/changelog/$slug'
      preLoaderRoute: typeof ChangelogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/billing/': {
      id: '/$orgSlug/billing/'
      path: '/billing'
      fullPath: '/$orgSlug/billing/'
      preLoaderRoute: typeof OrgSlugBillingIndexRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/customers/': {
      id: '/$orgSlug/customers/'
      path: '/customers'
      fullPath: '/$orgSlug/customers/'
      preLoaderRoute: typeof OrgSlugCustomersIndexRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/customers/$customerId': {
      id: '/$orgSlug/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/$orgSlug/customers/$customerId'
      preLoaderRoute: typeof OrgSlugCustomersCustomerIdRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/opd/': {
      id: '/$orgSlug/opd/'
      path: '/opd'
      fullPath: '/$orgSlug/opd/'
      preLoaderRoute: typeof OrgSlugOpdIndexRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/opd/$appointmentId': {
      id: '/$orgSlug/opd/$appointmentId'
      path: '/opd/$appointmentId'
      fullPath: '/$orgSlug/opd/$appointmentId'
      preLoaderRoute: typeof OrgSlugOpdAppointmentIdRouteRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/opd/new': {
      id: '/$orgSlug/opd/new'
      path: '/opd/new'
      fullPath: '/$orgSlug/opd/new'
      preLoaderRoute: typeof OrgSlugOpdNewRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/parties_/$partyId': {
      id: '/$orgSlug/parties_/$partyId'
      path: '/parties/$partyId'
      fullPath: '/$orgSlug/parties/$partyId'
      preLoaderRoute: typeof OrgSlugPartiesPartyIdRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/receipts/$receiptId': {
      id: '/$orgSlug/receipts/$receiptId'
      path: '/$receiptId'
      fullPath: '/$orgSlug/receipts/$receiptId'
      preLoaderRoute: typeof OrgSlugReceiptsReceiptIdRouteImport
      parentRoute: typeof OrgSlugReceiptsRouteRoute
    }
    '/$orgSlug/reports/': {
      id: '/$orgSlug/reports/'
      path: '/reports'
      fullPath: '/$orgSlug/reports/'
      preLoaderRoute: typeof OrgSlugReportsIndexRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/reports/balance-sheet': {
      id: '/$orgSlug/reports/balance-sheet'
      path: '/reports/balance-sheet'
      fullPath: '/$orgSlug/reports/balance-sheet'
      preLoaderRoute: typeof OrgSlugReportsBalanceSheetRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/reports/daily-collections': {
      id: '/$orgSlug/reports/daily-collections'
      path: '/reports/daily-collections'
      fullPath: '/$orgSlug/reports/daily-collections'
      preLoaderRoute: typeof OrgSlugReportsDailyCollectionsRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/reports/gst': {
      id: '/$orgSlug/reports/gst'
      path: '/reports/gst'
      fullPath: '/$orgSlug/reports/gst'
      preLoaderRoute: typeof OrgSlugReportsGstRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/reports/opd-register': {
      id: '/$orgSlug/reports/opd-register'
      path: '/reports/opd-register'
      fullPath: '/$orgSlug/reports/opd-register'
      preLoaderRoute: typeof OrgSlugReportsOpdRegisterRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/reports/trial-balance': {
      id: '/$orgSlug/reports/trial-balance'
      path: '/reports/trial-balance'
      fullPath: '/$orgSlug/reports/trial-balance'
      preLoaderRoute: typeof OrgSlugReportsTrialBalanceRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/settings/': {
      id: '/$orgSlug/settings/'
      path: '/'
      fullPath: '/$orgSlug/settings/'
      preLoaderRoute: typeof OrgSlugSettingsIndexRouteImport
      parentRoute: typeof OrgSlugSettingsRouteRoute
    }
    '/$orgSlug/settings/audit': {
      id: '/$orgSlug/settings/audit'
      path: '/audit'
      fullPath: '/$orgSlug/settings/audit'
      preLoaderRoute: typeof OrgSlugSettingsAuditRouteImport
      parentRoute: typeof OrgSlugSettingsRouteRoute
    }
    '/$orgSlug/settings/items': {
      id: '/$orgSlug/settings/items'
      path: '/items'
      fullPath: '/$orgSlug/settings/items'
      preLoaderRoute: typeof OrgSlugSettingsItemsRouteImport
      parentRoute: typeof OrgSlugSettingsRouteRoute
    }
    '/$orgSlug/settings/members': {
      id: '/$orgSlug/settings/members'
      path: '/members'
      fullPath: '/$orgSlug/settings/members'
      preLoaderRoute: typeof OrgSlugSettingsMembersRouteImport
      parentRoute: typeof OrgSlugSettingsRouteRoute
    }
    '/$orgSlug/settings/organization': {
      id: '/$orgSlug/settings/organization'
      path: '/organization'
      fullPath: '/$orgSlug/settings/organization'
      preLoaderRoute: typeof OrgSlugSettingsOrganizationRouteImport
      parentRoute: typeof OrgSlugSettingsRouteRoute
    }
    '/$orgSlug/settings/payers': {
      id: '/$orgSlug/settings/payers'
      path: '/payers'
      fullPath: '/$orgSlug/settings/payers'
      preLoaderRoute: typeof OrgSlugSettingsPayersRouteImport
      parentRoute: typeof OrgSlugSettingsRouteRoute
    }
    '/$orgSlug/settings/staff': {
      id: '/$orgSlug/settings/staff'
      path: '/staff'
      fullPath: '/$orgSlug/settings/staff'
      preLoaderRoute: typeof OrgSlugSettingsStaffRouteImport
      parentRoute: typeof OrgSlugSettingsRouteRoute
    }
    '/$orgSlug/billing/invoices/$invoiceId': {
      id: '/$orgSlug/billing/invoices/$invoiceId'
      path: '/billing/invoices/$invoiceId'
      fullPath: '/$orgSlug/billing/invoices/$invoiceId'
      preLoaderRoute: typeof OrgSlugBillingInvoicesInvoiceIdRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/opd/$appointmentId/': {
      id: '/$orgSlug/opd/$appointmentId/'
      path: '/'
      fullPath: '/$orgSlug/opd/$appointmentId/'
      preLoaderRoute: typeof OrgSlugOpdAppointmentIdIndexRouteImport
      parentRoute: typeof OrgSlugOpdAppointmentIdRouteRoute
    }
    '/$orgSlug/opd/$appointmentId/billing': {
      id: '/$orgSlug/opd/$appointmentId/billing'
      path: '/billing'
      fullPath: '/$orgSlug/opd/$appointmentId/billing'
      preLoaderRoute: typeof OrgSlugOpdAppointmentIdBillingRouteImport
      parentRoute: typeof OrgSlugOpdAppointmentIdRouteRoute
    }
    '/$orgSlug/parties_/$partyId/': {
      id: '/$orgSlug/parties_/$partyId/'
      path: '/'
      fullPath: '/$orgSlug/parties/$partyId/'
      preLoaderRoute: typeof OrgSlugPartiesPartyIdIndexRouteImport
      parentRoute: typeof OrgSlugPartiesPartyIdRoute
    }
    '/$orgSlug/parties_/$partyId/ledger': {
      id: '/$orgSlug/parties_/$partyId/ledger'
      path: '/ledger'
      fullPath: '/$orgSlug/parties/$partyId/ledger'
      preLoaderRoute: typeof OrgSlugPartiesPartyIdLedgerRouteImport
      parentRoute: typeof OrgSlugPartiesPartyIdRoute
    }
    '/$orgSlug/parties_/$partyId/receipts': {
      id: '/$orgSlug/parties_/$partyId/receipts'
      path: '/receipts'
      fullPath: '/$orgSlug/parties/$partyId/receipts'
      preLoaderRoute: typeof OrgSlugPartiesPartyIdReceiptsRouteImport
      parentRoute: typeof OrgSlugPartiesPartyIdRoute
    }
    '/api/$orgSlug/receipts/$receiptId/pdf': {
      id: '/api/$orgSlug/receipts/$receiptId/pdf'
      path: '/api/$orgSlug/receipts/$receiptId/pdf'
      fullPath: '/api/$orgSlug/receipts/$receiptId/pdf'
      preLoaderRoute: typeof ApiOrgSlugReceiptsReceiptIdPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/billing/invoices/$invoiceId_/credit-note/$creditNoteId': {
      id: '/$orgSlug/billing/invoices/$invoiceId_/credit-note/$creditNoteId'
      path: '/billing/invoices/$invoiceId/credit-note/$creditNoteId'
      fullPath: '/$orgSlug/billing/invoices/$invoiceId/credit-note/$creditNoteId'
      preLoaderRoute: typeof OrgSlugBillingInvoicesInvoiceIdCreditNoteCreditNoteIdRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/billing/invoices/$invoiceId_/receipt/$paymentId': {
      id: '/$orgSlug/billing/invoices/$invoiceId_/receipt/$paymentId'
      path: '/billing/invoices/$invoiceId/receipt/$paymentId'
      fullPath: '/$orgSlug/billing/invoices/$invoiceId/receipt/$paymentId'
      preLoaderRoute: typeof OrgSlugBillingInvoicesInvoiceIdReceiptPaymentIdRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/billing/invoices/$invoiceId_/refund/$refundId': {
      id: '/$orgSlug/billing/invoices/$invoiceId_/refund/$refundId'
      path: '/billing/invoices/$invoiceId/refund/$refundId'
      fullPath: '/$orgSlug/billing/invoices/$invoiceId/refund/$refundId'
      preLoaderRoute: typeof OrgSlugBillingInvoicesInvoiceIdRefundRefundIdRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/api/$orgSlug/billing/invoices/$invoiceId/pdf': {
      id: '/api/$orgSlug/billing/invoices/$invoiceId/pdf'
      path: '/api/$orgSlug/billing/invoices/$invoiceId/pdf'
      fullPath: '/api/$orgSlug/billing/invoices/$invoiceId/pdf'
      preLoaderRoute: typeof ApiOrgSlugBillingInvoicesInvoiceIdPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OrgSlugReceiptsRouteRouteChildren {
  OrgSlugReceiptsReceiptIdRoute: typeof OrgSlugReceiptsReceiptIdRoute
}

const OrgSlugReceiptsRouteRouteChildren: OrgSlugReceiptsRouteRouteChildren = {
  OrgSlugReceiptsReceiptIdRoute: OrgSlugReceiptsReceiptIdRoute,
}

const OrgSlugReceiptsRouteRouteWithChildren =
  OrgSlugReceiptsRouteRoute._addFileChildren(OrgSlugReceiptsRouteRouteChildren)

interface OrgSlugSettingsRouteRouteChildren {
  OrgSlugSettingsAuditRoute: typeof OrgSlugSettingsAuditRoute
  OrgSlugSettingsItemsRoute: typeof OrgSlugSettingsItemsRoute
  OrgSlugSettingsMembersRoute: typeof OrgSlugSettingsMembersRoute
  OrgSlugSettingsOrganizationRoute: typeof OrgSlugSettingsOrganizationRoute
  OrgSlugSettingsPayersRoute: typeof OrgSlugSettingsPayersRoute
  OrgSlugSettingsStaffRoute: typeof OrgSlugSettingsStaffRoute
  OrgSlugSettingsIndexRoute: typeof OrgSlugSettingsIndexRoute
}

const OrgSlugSettingsRouteRouteChildren: OrgSlugSettingsRouteRouteChildren = {
  OrgSlugSettingsAuditRoute: OrgSlugSettingsAuditRoute,
  OrgSlugSettingsItemsRoute: OrgSlugSettingsItemsRoute,
  OrgSlugSettingsMembersRoute: OrgSlugSettingsMembersRoute,
  OrgSlugSettingsOrganizationRoute: OrgSlugSettingsOrganizationRoute,
  OrgSlugSettingsPayersRoute: OrgSlugSettingsPayersRoute,
  OrgSlugSettingsStaffRoute: OrgSlugSettingsStaffRoute,
  OrgSlugSettingsIndexRoute: OrgSlugSettingsIndexRoute,
}

const OrgSlugSettingsRouteRouteWithChildren =
  OrgSlugSettingsRouteRoute._addFileChildren(OrgSlugSettingsRouteRouteChildren)

interface OrgSlugOpdAppointmentIdRouteRouteChildren {
  OrgSlugOpdAppointmentIdBillingRoute: typeof OrgSlugOpdAppointmentIdBillingRoute
  OrgSlugOpdAppointmentIdIndexRoute: typeof OrgSlugOpdAppointmentIdIndexRoute
}

const OrgSlugOpdAppointmentIdRouteRouteChildren: OrgSlugOpdAppointmentIdRouteRouteChildren =
  {
    OrgSlugOpdAppointmentIdBillingRoute: OrgSlugOpdAppointmentIdBillingRoute,
    OrgSlugOpdAppointmentIdIndexRoute: OrgSlugOpdAppointmentIdIndexRoute,
  }

const OrgSlugOpdAppointmentIdRouteRouteWithChildren =
  OrgSlugOpdAppointmentIdRouteRoute._addFileChildren(
    OrgSlugOpdAppointmentIdRouteRouteChildren,
  )

interface OrgSlugPartiesPartyIdRouteChildren {
  OrgSlugPartiesPartyIdLedgerRoute: typeof OrgSlugPartiesPartyIdLedgerRoute
  OrgSlugPartiesPartyIdReceiptsRoute: typeof OrgSlugPartiesPartyIdReceiptsRoute
  OrgSlugPartiesPartyIdIndexRoute: typeof OrgSlugPartiesPartyIdIndexRoute
}

const OrgSlugPartiesPartyIdRouteChildren: OrgSlugPartiesPartyIdRouteChildren = {
  OrgSlugPartiesPartyIdLedgerRoute: OrgSlugPartiesPartyIdLedgerRoute,
  OrgSlugPartiesPartyIdReceiptsRoute: OrgSlugPartiesPartyIdReceiptsRoute,
  OrgSlugPartiesPartyIdIndexRoute: OrgSlugPartiesPartyIdIndexRoute,
}

const OrgSlugPartiesPartyIdRouteWithChildren =
  OrgSlugPartiesPartyIdRoute._addFileChildren(
    OrgSlugPartiesPartyIdRouteChildren,
  )

interface OrgSlugRouteRouteChildren {
  OrgSlugPartiesRouteRoute: typeof OrgSlugPartiesRouteRoute
  OrgSlugReceiptsRouteRoute: typeof OrgSlugReceiptsRouteRouteWithChildren
  OrgSlugSettingsRouteRoute: typeof OrgSlugSettingsRouteRouteWithChildren
  OrgSlugDashboardRoute: typeof OrgSlugDashboardRoute
  OrgSlugFilesRoute: typeof OrgSlugFilesRoute
  OrgSlugOnboardingRoute: typeof OrgSlugOnboardingRoute
  OrgSlugIndexRoute: typeof OrgSlugIndexRoute
  OrgSlugOpdAppointmentIdRouteRoute: typeof OrgSlugOpdAppointmentIdRouteRouteWithChildren
  OrgSlugCustomersCustomerIdRoute: typeof OrgSlugCustomersCustomerIdRoute
  OrgSlugOpdNewRoute: typeof OrgSlugOpdNewRoute
  OrgSlugPartiesPartyIdRoute: typeof OrgSlugPartiesPartyIdRouteWithChildren
  OrgSlugReportsBalanceSheetRoute: typeof OrgSlugReportsBalanceSheetRoute
  OrgSlugReportsDailyCollectionsRoute: typeof OrgSlugReportsDailyCollectionsRoute
  OrgSlugReportsGstRoute: typeof OrgSlugReportsGstRoute
  OrgSlugReportsOpdRegisterRoute: typeof OrgSlugReportsOpdRegisterRoute
  OrgSlugReportsTrialBalanceRoute: typeof OrgSlugReportsTrialBalanceRoute
  OrgSlugBillingIndexRoute: typeof OrgSlugBillingIndexRoute
  OrgSlugCustomersIndexRoute: typeof OrgSlugCustomersIndexRoute
  OrgSlugOpdIndexRoute: typeof OrgSlugOpdIndexRoute
  OrgSlugReportsIndexRoute: typeof OrgSlugReportsIndexRoute
  OrgSlugBillingInvoicesInvoiceIdRoute: typeof OrgSlugBillingInvoicesInvoiceIdRoute
  OrgSlugBillingInvoicesInvoiceIdCreditNoteCreditNoteIdRoute: typeof OrgSlugBillingInvoicesInvoiceIdCreditNoteCreditNoteIdRoute
  OrgSlugBillingInvoicesInvoiceIdReceiptPaymentIdRoute: typeof OrgSlugBillingInvoicesInvoiceIdReceiptPaymentIdRoute
  OrgSlugBillingInvoicesInvoiceIdRefundRefundIdRoute: typeof OrgSlugBillingInvoicesInvoiceIdRefundRefundIdRoute
}

const OrgSlugRouteRouteChildren: OrgSlugRouteRouteChildren = {
  OrgSlugPartiesRouteRoute: OrgSlugPartiesRouteRoute,
  OrgSlugReceiptsRouteRoute: OrgSlugReceiptsRouteRouteWithChildren,
  OrgSlugSettingsRouteRoute: OrgSlugSettingsRouteRouteWithChildren,
  OrgSlugDashboardRoute: OrgSlugDashboardRoute,
  OrgSlugFilesRoute: OrgSlugFilesRoute,
  OrgSlugOnboardingRoute: OrgSlugOnboardingRoute,
  OrgSlugIndexRoute: OrgSlugIndexRoute,
  OrgSlugOpdAppointmentIdRouteRoute:
    OrgSlugOpdAppointmentIdRouteRouteWithChildren,
  OrgSlugCustomersCustomerIdRoute: OrgSlugCustomersCustomerIdRoute,
  OrgSlugOpdNewRoute: OrgSlugOpdNewRoute,
  OrgSlugPartiesPartyIdRoute: OrgSlugPartiesPartyIdRouteWithChildren,
  OrgSlugReportsBalanceSheetRoute: OrgSlugReportsBalanceSheetRoute,
  OrgSlugReportsDailyCollectionsRoute: OrgSlugReportsDailyCollectionsRoute,
  OrgSlugReportsGstRoute: OrgSlugReportsGstRoute,
  OrgSlugReportsOpdRegisterRoute: OrgSlugReportsOpdRegisterRoute,
  OrgSlugReportsTrialBalanceRoute: OrgSlugReportsTrialBalanceRoute,
  OrgSlugBillingIndexRoute: OrgSlugBillingIndexRoute,
  OrgSlugCustomersIndexRoute: OrgSlugCustomersIndexRoute,
  OrgSlugOpdIndexRoute: OrgSlugOpdIndexRoute,
  OrgSlugReportsIndexRoute: OrgSlugReportsIndexRoute,
  OrgSlugBillingInvoicesInvoiceIdRoute: OrgSlugBillingInvoicesInvoiceIdRoute,
  OrgSlugBillingInvoicesInvoiceIdCreditNoteCreditNoteIdRoute:
    OrgSlugBillingInvoicesInvoiceIdCreditNoteCreditNoteIdRoute,
  OrgSlugBillingInvoicesInvoiceIdReceiptPaymentIdRoute:
    OrgSlugBillingInvoicesInvoiceIdReceiptPaymentIdRoute,
  OrgSlugBillingInvoicesInvoiceIdRefundRefundIdRoute:
    OrgSlugBillingInvoicesInvoiceIdRefundRefundIdRoute,
}

const OrgSlugRouteRouteWithChildren = OrgSlugRouteRoute._addFileChildren(
  OrgSlugRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrgSlugRouteRoute: OrgSlugRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  BillingRoute: BillingRoute,
  ContactRoute: ContactRoute,
  CreateRoute: CreateRoute,
  CustomersRoute: CustomersRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ChangelogSlugRoute: ChangelogSlugRoute,
  ChangelogIndexRoute: ChangelogIndexRoute,
  ApiOrgSlugReceiptsReceiptIdPdfRoute: ApiOrgSlugReceiptsReceiptIdPdfRoute,
  ApiOrgSlugBillingInvoicesInvoiceIdPdfRoute:
    ApiOrgSlugBillingInvoicesInvoiceIdPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
