/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrgSlugRouteRouteImport } from './routes/$orgSlug/route'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as CreateRouteImport } from './routes/create'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OrgSlugIndexRouteImport } from './routes/$orgSlug/index'
import { Route as OrgSlugAccountsRouteImport } from './routes/$orgSlug/accounts'
import { Route as OrgSlugBankingRouteImport } from './routes/$orgSlug/banking'
import { Route as OrgSlugBillsRouteRouteImport } from './routes/$orgSlug/bills/route'
import { Route as OrgSlugInvoicesRouteRouteImport } from './routes/$orgSlug/invoices/route'
import { Route as OrgSlugItemsRouteImport } from './routes/$orgSlug/items'
import { Route as OrgSlugJournalsRouteImport } from './routes/$orgSlug/journals'
import { Route as OrgSlugNotesRouteRouteImport } from './routes/$orgSlug/notes/route'
import { Route as OrgSlugOnboardingRouteImport } from './routes/$orgSlug/onboarding'
import { Route as OrgSlugPartiesRouteRouteImport } from './routes/$orgSlug/parties/route'
import { Route as OrgSlugPaymentsRouteRouteImport } from './routes/$orgSlug/payments/route'
import { Route as OrgSlugReceiptsRouteRouteImport } from './routes/$orgSlug/receipts/route'
import { Route as OrgSlugReportsRouteImport } from './routes/$orgSlug/reports'
import { Route as OrgSlugSettingsRouteRouteImport } from './routes/$orgSlug/settings/route'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteAboutRouteImport } from './routes/_site/about'
import { Route as SiteBillingRouteImport } from './routes/_site/billing'
import { Route as SiteCasRouteImport } from './routes/_site/cas'
import { Route as SiteContactRouteImport } from './routes/_site/contact'
import { Route as SiteCustomersRouteImport } from './routes/_site/customers'
import { Route as SiteEarlyAccessRouteImport } from './routes/_site/early-access'
import { Route as SitePricingRouteImport } from './routes/_site/pricing'
import { Route as SitePrivacyRouteImport } from './routes/_site/privacy'
import { Route as SiteTallyRouteImport } from './routes/_site/tally'
import { Route as OrgSlugBillsBillIdRouteImport } from './routes/$orgSlug/bills/$billId'
import { Route as OrgSlugBillsNewRouteImport } from './routes/$orgSlug/bills_.new'
import { Route as OrgSlugInvoicesInvoiceIdRouteImport } from './routes/$orgSlug/invoices/$invoiceId'
import { Route as OrgSlugInvoicesNewRouteImport } from './routes/$orgSlug/invoices_.new'
import { Route as OrgSlugJournalsJournalIdRouteImport } from './routes/$orgSlug/journals_.$journalId'
import { Route as OrgSlugJournalsNewRouteImport } from './routes/$orgSlug/journals_.new'
import { Route as OrgSlugNotesNoteIdRouteImport } from './routes/$orgSlug/notes/$noteId'
import { Route as OrgSlugNotesNewRouteImport } from './routes/$orgSlug/notes_.new'
import { Route as OrgSlugPartiesPartyIdRouteImport } from './routes/$orgSlug/parties_.$partyId'
import { Route as OrgSlugPaymentsPaymentIdRouteImport } from './routes/$orgSlug/payments/$paymentId'
import { Route as OrgSlugReceiptsReceiptIdRouteImport } from './routes/$orgSlug/receipts/$receiptId'
import { Route as OrgSlugReportsAccountLedgerRouteImport } from './routes/$orgSlug/reports_.account-ledger'
import { Route as OrgSlugReportsBalanceSheetRouteImport } from './routes/$orgSlug/reports_.balance-sheet'
import { Route as OrgSlugReportsDayBookRouteImport } from './routes/$orgSlug/reports_.day-book'
import { Route as OrgSlugReportsProfitAndLossRouteImport } from './routes/$orgSlug/reports_.profit-and-loss'
import { Route as OrgSlugReportsTrialBalanceRouteImport } from './routes/$orgSlug/reports_.trial-balance'
import { Route as OrgSlugSettingsIndexRouteImport } from './routes/$orgSlug/settings/index'
import { Route as OrgSlugSettingsAuditRouteImport } from './routes/$orgSlug/settings/audit'
import { Route as OrgSlugSettingsFilesRouteImport } from './routes/$orgSlug/settings/files'
import { Route as OrgSlugSettingsImportRouteImport } from './routes/$orgSlug/settings/import'
import { Route as OrgSlugSettingsLocksRouteImport } from './routes/$orgSlug/settings/locks'
import { Route as OrgSlugSettingsMembersRouteImport } from './routes/$orgSlug/settings/members'
import { Route as OrgSlugSettingsOpeningBalanceRouteImport } from './routes/$orgSlug/settings/opening-balance'
import { Route as OrgSlugSettingsOrganizationRouteImport } from './routes/$orgSlug/settings/organization'
import { Route as SiteChangelogIndexRouteImport } from './routes/_site/changelog.index'
import { Route as SiteChangelogSlugRouteImport } from './routes/_site/changelog.$slug'
import { Route as OrgSlugBillsBillIdEditRouteImport } from './routes/$orgSlug/bills_.$billId.edit'
import { Route as OrgSlugInvoicesInvoiceIdEditRouteImport } from './routes/$orgSlug/invoices_.$invoiceId.edit'
import { Route as OrgSlugPartiesPartyIdIndexRouteImport } from './routes/$orgSlug/parties_.$partyId.index'
import { Route as OrgSlugPartiesPartyIdLedgerRouteImport } from './routes/$orgSlug/parties_.$partyId.ledger'
import { Route as OrgSlugPartiesPartyIdTransactionsRouteImport } from './routes/$orgSlug/parties_.$partyId.transactions'
import { Route as ApiOrgSlugInvoicesInvoiceIdPdfRouteImport } from './routes/api.$orgSlug.invoices.$invoiceId.pdf'
import { Route as ApiOrgSlugNotesNoteIdPdfRouteImport } from './routes/api.$orgSlug.notes.$noteId.pdf'
import { Route as ApiOrgSlugReceiptsReceiptIdPdfRouteImport } from './routes/api.$orgSlug.receipts.$receiptId.pdf'
import { Route as ApiOrgSlugReportsAccountLedgerPdfRouteImport } from './routes/api.$orgSlug.reports.account-ledger.pdf'
import { Route as ApiOrgSlugReportsBalanceSheetPdfRouteImport } from './routes/api.$orgSlug.reports.balance-sheet.pdf'
import { Route as ApiOrgSlugReportsDayBookPdfRouteImport } from './routes/api.$orgSlug.reports.day-book.pdf'
import { Route as ApiOrgSlugReportsProfitAndLossPdfRouteImport } from './routes/api.$orgSlug.reports.profit-and-loss.pdf'
import { Route as ApiOrgSlugReportsTrialBalancePdfRouteImport } from './routes/api.$orgSlug.reports.trial-balance.pdf'
import { Route as ApiOrgSlugPartiesPartyIdStatementPdfRouteImport } from './routes/api.$orgSlug.parties.$partyId.statement.pdf'

const OrgSlugRouteRoute = OrgSlugRouteRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugIndexRoute = OrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugAccountsRoute = OrgSlugAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugBankingRoute = OrgSlugBankingRouteImport.update({
  id: '/banking',
  path: '/banking',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugBillsRouteRoute = OrgSlugBillsRouteRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugInvoicesRouteRoute = OrgSlugInvoicesRouteRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugItemsRoute = OrgSlugItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugJournalsRoute = OrgSlugJournalsRouteImport.update({
  id: '/journals',
  path: '/journals',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugNotesRouteRoute = OrgSlugNotesRouteRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugOnboardingRoute = OrgSlugOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugPartiesRouteRoute = OrgSlugPartiesRouteRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugPaymentsRouteRoute = OrgSlugPaymentsRouteRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugReceiptsRouteRoute = OrgSlugReceiptsRouteRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugReportsRoute = OrgSlugReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugSettingsRouteRoute = OrgSlugSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBillingRoute = SiteBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCasRoute = SiteCasRouteImport.update({
  id: '/cas',
  path: '/cas',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCustomersRoute = SiteCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEarlyAccessRoute = SiteEarlyAccessRouteImport.update({
  id: '/early-access',
  path: '/early-access',
  getParentRoute: () => SiteRoute,
} as any)
const SitePricingRoute = SitePricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => SiteRoute,
} as any)
const SitePrivacyRoute = SitePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTallyRoute = SiteTallyRouteImport.update({
  id: '/tally',
  path: '/tally',
  getParentRoute: () => SiteRoute,
} as any)
const OrgSlugBillsBillIdRoute = OrgSlugBillsBillIdRouteImport.update({
  id: '/$billId',
  path: '/$billId',
  getParentRoute: () => OrgSlugBillsRouteRoute,
} as any)
const OrgSlugBillsNewRoute = OrgSlugBillsNewRouteImport.update({
  id: '/bills_/new',
  path: '/bills/new',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugInvoicesInvoiceIdRoute =
  OrgSlugInvoicesInvoiceIdRouteImport.update({
    id: '/$invoiceId',
    path: '/$invoiceId',
    getParentRoute: () => OrgSlugInvoicesRouteRoute,
  } as any)
const OrgSlugInvoicesNewRoute = OrgSlugInvoicesNewRouteImport.update({
  id: '/invoices_/new',
  path: '/invoices/new',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugJournalsJournalIdRoute =
  OrgSlugJournalsJournalIdRouteImport.update({
    id: '/journals_/$journalId',
    path: '/journals/$journalId',
    getParentRoute: () => OrgSlugRouteRoute,
  } as any)
const OrgSlugJournalsNewRoute = OrgSlugJournalsNewRouteImport.update({
  id: '/journals_/new',
  path: '/journals/new',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugNotesNoteIdRoute = OrgSlugNotesNoteIdRouteImport.update({
  id: '/$noteId',
  path: '/$noteId',
  getParentRoute: () => OrgSlugNotesRouteRoute,
} as any)
const OrgSlugNotesNewRoute = OrgSlugNotesNewRouteImport.update({
  id: '/notes_/new',
  path: '/notes/new',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugPartiesPartyIdRoute = OrgSlugPartiesPartyIdRouteImport.update({
  id: '/parties_/$partyId',
  path: '/parties/$partyId',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugPaymentsPaymentIdRoute =
  OrgSlugPaymentsPaymentIdRouteImport.update({
    id: '/$paymentId',
    path: '/$paymentId',
    getParentRoute: () => OrgSlugPaymentsRouteRoute,
  } as any)
const OrgSlugReceiptsReceiptIdRoute =
  OrgSlugReceiptsReceiptIdRouteImport.update({
    id: '/$receiptId',
    path: '/$receiptId',
    getParentRoute: () => OrgSlugReceiptsRouteRoute,
  } as any)
const OrgSlugReportsAccountLedgerRoute =
  OrgSlugReportsAccountLedgerRouteImport.update({
    id: '/reports_/account-ledger',
    path: '/reports/account-ledger',
    getParentRoute: () => OrgSlugRouteRoute,
  } as any)
const OrgSlugReportsBalanceSheetRoute =
  OrgSlugReportsBalanceSheetRouteImport.update({
    id: '/reports_/balance-sheet',
    path: '/reports/balance-sheet',
    getParentRoute: () => OrgSlugRouteRoute,
  } as any)
const OrgSlugReportsDayBookRoute = OrgSlugReportsDayBookRouteImport.update({
  id: '/reports_/day-book',
  path: '/reports/day-book',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugReportsProfitAndLossRoute =
  OrgSlugReportsProfitAndLossRouteImport.update({
    id: '/reports_/profit-and-loss',
    path: '/reports/profit-and-loss',
    getParentRoute: () => OrgSlugRouteRoute,
  } as any)
const OrgSlugReportsTrialBalanceRoute =
  OrgSlugReportsTrialBalanceRouteImport.update({
    id: '/reports_/trial-balance',
    path: '/reports/trial-balance',
    getParentRoute: () => OrgSlugRouteRoute,
  } as any)
const OrgSlugSettingsIndexRoute = OrgSlugSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgSlugSettingsRouteRoute,
} as any)
const OrgSlugSettingsAuditRoute = OrgSlugSettingsAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => OrgSlugSettingsRouteRoute,
} as any)
const OrgSlugSettingsFilesRoute = OrgSlugSettingsFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => OrgSlugSettingsRouteRoute,
} as any)
const OrgSlugSettingsImportRoute = OrgSlugSettingsImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => OrgSlugSettingsRouteRoute,
} as any)
const OrgSlugSettingsLocksRoute = OrgSlugSettingsLocksRouteImport.update({
  id: '/locks',
  path: '/locks',
  getParentRoute: () => OrgSlugSettingsRouteRoute,
} as any)
const OrgSlugSettingsMembersRoute = OrgSlugSettingsMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => OrgSlugSettingsRouteRoute,
} as any)
const OrgSlugSettingsOpeningBalanceRoute =
  OrgSlugSettingsOpeningBalanceRouteImport.update({
    id: '/opening-balance',
    path: '/opening-balance',
    getParentRoute: () => OrgSlugSettingsRouteRoute,
  } as any)
const OrgSlugSettingsOrganizationRoute =
  OrgSlugSettingsOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => OrgSlugSettingsRouteRoute,
  } as any)
const SiteChangelogIndexRoute = SiteChangelogIndexRouteImport.update({
  id: '/changelog/',
  path: '/changelog/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteChangelogSlugRoute = SiteChangelogSlugRouteImport.update({
  id: '/changelog/$slug',
  path: '/changelog/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const OrgSlugBillsBillIdEditRoute = OrgSlugBillsBillIdEditRouteImport.update({
  id: '/bills_/$billId/edit',
  path: '/bills/$billId/edit',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugInvoicesInvoiceIdEditRoute =
  OrgSlugInvoicesInvoiceIdEditRouteImport.update({
    id: '/invoices_/$invoiceId/edit',
    path: '/invoices/$invoiceId/edit',
    getParentRoute: () => OrgSlugRouteRoute,
  } as any)
const OrgSlugPartiesPartyIdIndexRoute =
  OrgSlugPartiesPartyIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrgSlugPartiesPartyIdRoute,
  } as any)
const OrgSlugPartiesPartyIdLedgerRoute =
  OrgSlugPartiesPartyIdLedgerRouteImport.update({
    id: '/ledger',
    path: '/ledger',
    getParentRoute: () => OrgSlugPartiesPartyIdRoute,
  } as any)
const OrgSlugPartiesPartyIdTransactionsRoute =
  OrgSlugPartiesPartyIdTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => OrgSlugPartiesPartyIdRoute,
  } as any)
const ApiOrgSlugInvoicesInvoiceIdPdfRoute =
  ApiOrgSlugInvoicesInvoiceIdPdfRouteImport.update({
    id: '/api/$orgSlug/invoices/$invoiceId/pdf',
    path: '/api/$orgSlug/invoices/$invoiceId/pdf',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrgSlugNotesNoteIdPdfRoute =
  ApiOrgSlugNotesNoteIdPdfRouteImport.update({
    id: '/api/$orgSlug/notes/$noteId/pdf',
    path: '/api/$orgSlug/notes/$noteId/pdf',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrgSlugReceiptsReceiptIdPdfRoute =
  ApiOrgSlugReceiptsReceiptIdPdfRouteImport.update({
    id: '/api/$orgSlug/receipts/$receiptId/pdf',
    path: '/api/$orgSlug/receipts/$receiptId/pdf',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrgSlugReportsAccountLedgerPdfRoute =
  ApiOrgSlugReportsAccountLedgerPdfRouteImport.update({
    id: '/api/$orgSlug/reports/account-ledger/pdf',
    path: '/api/$orgSlug/reports/account-ledger/pdf',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrgSlugReportsBalanceSheetPdfRoute =
  ApiOrgSlugReportsBalanceSheetPdfRouteImport.update({
    id: '/api/$orgSlug/reports/balance-sheet/pdf',
    path: '/api/$orgSlug/reports/balance-sheet/pdf',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrgSlugReportsDayBookPdfRoute =
  ApiOrgSlugReportsDayBookPdfRouteImport.update({
    id: '/api/$orgSlug/reports/day-book/pdf',
    path: '/api/$orgSlug/reports/day-book/pdf',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrgSlugReportsProfitAndLossPdfRoute =
  ApiOrgSlugReportsProfitAndLossPdfRouteImport.update({
    id: '/api/$orgSlug/reports/profit-and-loss/pdf',
    path: '/api/$orgSlug/reports/profit-and-loss/pdf',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrgSlugReportsTrialBalancePdfRoute =
  ApiOrgSlugReportsTrialBalancePdfRouteImport.update({
    id: '/api/$orgSlug/reports/trial-balance/pdf',
    path: '/api/$orgSlug/reports/trial-balance/pdf',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrgSlugPartiesPartyIdStatementPdfRoute =
  ApiOrgSlugPartiesPartyIdStatementPdfRouteImport.update({
    id: '/api/$orgSlug/parties/$partyId/statement/pdf',
    path: '/api/$orgSlug/parties/$partyId/statement/pdf',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/$orgSlug': typeof OrgSlugRouteRouteWithChildren
  '/': typeof SiteIndexRoute
  '/create': typeof CreateRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$orgSlug/bills': typeof OrgSlugBillsRouteRouteWithChildren
  '/$orgSlug/invoices': typeof OrgSlugInvoicesRouteRouteWithChildren
  '/$orgSlug/notes': typeof OrgSlugNotesRouteRouteWithChildren
  '/$orgSlug/parties': typeof OrgSlugPartiesRouteRoute
  '/$orgSlug/payments': typeof OrgSlugPaymentsRouteRouteWithChildren
  '/$orgSlug/receipts': typeof OrgSlugReceiptsRouteRouteWithChildren
  '/$orgSlug/settings': typeof OrgSlugSettingsRouteRouteWithChildren
  '/$orgSlug/accounts': typeof OrgSlugAccountsRoute
  '/$orgSlug/banking': typeof OrgSlugBankingRoute
  '/$orgSlug/items': typeof OrgSlugItemsRoute
  '/$orgSlug/journals': typeof OrgSlugJournalsRoute
  '/$orgSlug/onboarding': typeof OrgSlugOnboardingRoute
  '/$orgSlug/reports': typeof OrgSlugReportsRoute
  '/about': typeof SiteAboutRoute
  '/billing': typeof SiteBillingRoute
  '/cas': typeof SiteCasRoute
  '/contact': typeof SiteContactRoute
  '/customers': typeof SiteCustomersRoute
  '/early-access': typeof SiteEarlyAccessRoute
  '/pricing': typeof SitePricingRoute
  '/privacy': typeof SitePrivacyRoute
  '/tally': typeof SiteTallyRoute
  '/$orgSlug/': typeof OrgSlugIndexRoute
  '/$orgSlug/bills/$billId': typeof OrgSlugBillsBillIdRoute
  '/$orgSlug/bills/new': typeof OrgSlugBillsNewRoute
  '/$orgSlug/invoices/$invoiceId': typeof OrgSlugInvoicesInvoiceIdRoute
  '/$orgSlug/invoices/new': typeof OrgSlugInvoicesNewRoute
  '/$orgSlug/journals/$journalId': typeof OrgSlugJournalsJournalIdRoute
  '/$orgSlug/journals/new': typeof OrgSlugJournalsNewRoute
  '/$orgSlug/notes/$noteId': typeof OrgSlugNotesNoteIdRoute
  '/$orgSlug/notes/new': typeof OrgSlugNotesNewRoute
  '/$orgSlug/parties/$partyId': typeof OrgSlugPartiesPartyIdRouteWithChildren
  '/$orgSlug/payments/$paymentId': typeof OrgSlugPaymentsPaymentIdRoute
  '/$orgSlug/receipts/$receiptId': typeof OrgSlugReceiptsReceiptIdRoute
  '/$orgSlug/reports/account-ledger': typeof OrgSlugReportsAccountLedgerRoute
  '/$orgSlug/reports/balance-sheet': typeof OrgSlugReportsBalanceSheetRoute
  '/$orgSlug/reports/day-book': typeof OrgSlugReportsDayBookRoute
  '/$orgSlug/reports/profit-and-loss': typeof OrgSlugReportsProfitAndLossRoute
  '/$orgSlug/reports/trial-balance': typeof OrgSlugReportsTrialBalanceRoute
  '/$orgSlug/settings/audit': typeof OrgSlugSettingsAuditRoute
  '/$orgSlug/settings/files': typeof OrgSlugSettingsFilesRoute
  '/$orgSlug/settings/import': typeof OrgSlugSettingsImportRoute
  '/$orgSlug/settings/locks': typeof OrgSlugSettingsLocksRoute
  '/$orgSlug/settings/members': typeof OrgSlugSettingsMembersRoute
  '/$orgSlug/settings/opening-balance': typeof OrgSlugSettingsOpeningBalanceRoute
  '/$orgSlug/settings/organization': typeof OrgSlugSettingsOrganizationRoute
  '/changelog/$slug': typeof SiteChangelogSlugRoute
  '/$orgSlug/settings/': typeof OrgSlugSettingsIndexRoute
  '/changelog/': typeof SiteChangelogIndexRoute
  '/$orgSlug/bills/$billId/edit': typeof OrgSlugBillsBillIdEditRoute
  '/$orgSlug/invoices/$invoiceId/edit': typeof OrgSlugInvoicesInvoiceIdEditRoute
  '/$orgSlug/parties/$partyId/ledger': typeof OrgSlugPartiesPartyIdLedgerRoute
  '/$orgSlug/parties/$partyId/transactions': typeof OrgSlugPartiesPartyIdTransactionsRoute
  '/$orgSlug/parties/$partyId/': typeof OrgSlugPartiesPartyIdIndexRoute
  '/api/$orgSlug/invoices/$invoiceId/pdf': typeof ApiOrgSlugInvoicesInvoiceIdPdfRoute
  '/api/$orgSlug/notes/$noteId/pdf': typeof ApiOrgSlugNotesNoteIdPdfRoute
  '/api/$orgSlug/receipts/$receiptId/pdf': typeof ApiOrgSlugReceiptsReceiptIdPdfRoute
  '/api/$orgSlug/reports/account-ledger/pdf': typeof ApiOrgSlugReportsAccountLedgerPdfRoute
  '/api/$orgSlug/reports/balance-sheet/pdf': typeof ApiOrgSlugReportsBalanceSheetPdfRoute
  '/api/$orgSlug/reports/day-book/pdf': typeof ApiOrgSlugReportsDayBookPdfRoute
  '/api/$orgSlug/reports/profit-and-loss/pdf': typeof ApiOrgSlugReportsProfitAndLossPdfRoute
  '/api/$orgSlug/reports/trial-balance/pdf': typeof ApiOrgSlugReportsTrialBalancePdfRoute
  '/api/$orgSlug/parties/$partyId/statement/pdf': typeof ApiOrgSlugPartiesPartyIdStatementPdfRoute
}
export interface FileRoutesByTo {
  '/create': typeof CreateRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$orgSlug/bills': typeof OrgSlugBillsRouteRouteWithChildren
  '/$orgSlug/invoices': typeof OrgSlugInvoicesRouteRouteWithChildren
  '/$orgSlug/notes': typeof OrgSlugNotesRouteRouteWithChildren
  '/$orgSlug/parties': typeof OrgSlugPartiesRouteRoute
  '/$orgSlug/payments': typeof OrgSlugPaymentsRouteRouteWithChildren
  '/$orgSlug/receipts': typeof OrgSlugReceiptsRouteRouteWithChildren
  '/$orgSlug/accounts': typeof OrgSlugAccountsRoute
  '/$orgSlug/banking': typeof OrgSlugBankingRoute
  '/$orgSlug/items': typeof OrgSlugItemsRoute
  '/$orgSlug/journals': typeof OrgSlugJournalsRoute
  '/$orgSlug/onboarding': typeof OrgSlugOnboardingRoute
  '/$orgSlug/reports': typeof OrgSlugReportsRoute
  '/about': typeof SiteAboutRoute
  '/billing': typeof SiteBillingRoute
  '/cas': typeof SiteCasRoute
  '/contact': typeof SiteContactRoute
  '/customers': typeof SiteCustomersRoute
  '/early-access': typeof SiteEarlyAccessRoute
  '/pricing': typeof SitePricingRoute
  '/privacy': typeof SitePrivacyRoute
  '/tally': typeof SiteTallyRoute
  '/$orgSlug': typeof OrgSlugIndexRoute
  '/': typeof SiteIndexRoute
  '/$orgSlug/bills/$billId': typeof OrgSlugBillsBillIdRoute
  '/$orgSlug/bills/new': typeof OrgSlugBillsNewRoute
  '/$orgSlug/invoices/$invoiceId': typeof OrgSlugInvoicesInvoiceIdRoute
  '/$orgSlug/invoices/new': typeof OrgSlugInvoicesNewRoute
  '/$orgSlug/journals/$journalId': typeof OrgSlugJournalsJournalIdRoute
  '/$orgSlug/journals/new': typeof OrgSlugJournalsNewRoute
  '/$orgSlug/notes/$noteId': typeof OrgSlugNotesNoteIdRoute
  '/$orgSlug/notes/new': typeof OrgSlugNotesNewRoute
  '/$orgSlug/payments/$paymentId': typeof OrgSlugPaymentsPaymentIdRoute
  '/$orgSlug/receipts/$receiptId': typeof OrgSlugReceiptsReceiptIdRoute
  '/$orgSlug/reports/account-ledger': typeof OrgSlugReportsAccountLedgerRoute
  '/$orgSlug/reports/balance-sheet': typeof OrgSlugReportsBalanceSheetRoute
  '/$orgSlug/reports/day-book': typeof OrgSlugReportsDayBookRoute
  '/$orgSlug/reports/profit-and-loss': typeof OrgSlugReportsProfitAndLossRoute
  '/$orgSlug/reports/trial-balance': typeof OrgSlugReportsTrialBalanceRoute
  '/$orgSlug/settings/audit': typeof OrgSlugSettingsAuditRoute
  '/$orgSlug/settings/files': typeof OrgSlugSettingsFilesRoute
  '/$orgSlug/settings/import': typeof OrgSlugSettingsImportRoute
  '/$orgSlug/settings/locks': typeof OrgSlugSettingsLocksRoute
  '/$orgSlug/settings/members': typeof OrgSlugSettingsMembersRoute
  '/$orgSlug/settings/opening-balance': typeof OrgSlugSettingsOpeningBalanceRoute
  '/$orgSlug/settings/organization': typeof OrgSlugSettingsOrganizationRoute
  '/changelog/$slug': typeof SiteChangelogSlugRoute
  '/$orgSlug/settings': typeof OrgSlugSettingsIndexRoute
  '/changelog': typeof SiteChangelogIndexRoute
  '/$orgSlug/bills/$billId/edit': typeof OrgSlugBillsBillIdEditRoute
  '/$orgSlug/invoices/$invoiceId/edit': typeof OrgSlugInvoicesInvoiceIdEditRoute
  '/$orgSlug/parties/$partyId/ledger': typeof OrgSlugPartiesPartyIdLedgerRoute
  '/$orgSlug/parties/$partyId/transactions': typeof OrgSlugPartiesPartyIdTransactionsRoute
  '/$orgSlug/parties/$partyId': typeof OrgSlugPartiesPartyIdIndexRoute
  '/api/$orgSlug/invoices/$invoiceId/pdf': typeof ApiOrgSlugInvoicesInvoiceIdPdfRoute
  '/api/$orgSlug/notes/$noteId/pdf': typeof ApiOrgSlugNotesNoteIdPdfRoute
  '/api/$orgSlug/receipts/$receiptId/pdf': typeof ApiOrgSlugReceiptsReceiptIdPdfRoute
  '/api/$orgSlug/reports/account-ledger/pdf': typeof ApiOrgSlugReportsAccountLedgerPdfRoute
  '/api/$orgSlug/reports/balance-sheet/pdf': typeof ApiOrgSlugReportsBalanceSheetPdfRoute
  '/api/$orgSlug/reports/day-book/pdf': typeof ApiOrgSlugReportsDayBookPdfRoute
  '/api/$orgSlug/reports/profit-and-loss/pdf': typeof ApiOrgSlugReportsProfitAndLossPdfRoute
  '/api/$orgSlug/reports/trial-balance/pdf': typeof ApiOrgSlugReportsTrialBalancePdfRoute
  '/api/$orgSlug/parties/$partyId/statement/pdf': typeof ApiOrgSlugPartiesPartyIdStatementPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$orgSlug': typeof OrgSlugRouteRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/create': typeof CreateRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$orgSlug/bills': typeof OrgSlugBillsRouteRouteWithChildren
  '/$orgSlug/invoices': typeof OrgSlugInvoicesRouteRouteWithChildren
  '/$orgSlug/notes': typeof OrgSlugNotesRouteRouteWithChildren
  '/$orgSlug/parties': typeof OrgSlugPartiesRouteRoute
  '/$orgSlug/payments': typeof OrgSlugPaymentsRouteRouteWithChildren
  '/$orgSlug/receipts': typeof OrgSlugReceiptsRouteRouteWithChildren
  '/$orgSlug/settings': typeof OrgSlugSettingsRouteRouteWithChildren
  '/$orgSlug/accounts': typeof OrgSlugAccountsRoute
  '/$orgSlug/banking': typeof OrgSlugBankingRoute
  '/$orgSlug/items': typeof OrgSlugItemsRoute
  '/$orgSlug/journals': typeof OrgSlugJournalsRoute
  '/$orgSlug/onboarding': typeof OrgSlugOnboardingRoute
  '/$orgSlug/reports': typeof OrgSlugReportsRoute
  '/_site/about': typeof SiteAboutRoute
  '/_site/billing': typeof SiteBillingRoute
  '/_site/cas': typeof SiteCasRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/customers': typeof SiteCustomersRoute
  '/_site/early-access': typeof SiteEarlyAccessRoute
  '/_site/pricing': typeof SitePricingRoute
  '/_site/privacy': typeof SitePrivacyRoute
  '/_site/tally': typeof SiteTallyRoute
  '/$orgSlug/': typeof OrgSlugIndexRoute
  '/_site/': typeof SiteIndexRoute
  '/$orgSlug/bills/$billId': typeof OrgSlugBillsBillIdRoute
  '/$orgSlug/bills_/new': typeof OrgSlugBillsNewRoute
  '/$orgSlug/invoices/$invoiceId': typeof OrgSlugInvoicesInvoiceIdRoute
  '/$orgSlug/invoices_/new': typeof OrgSlugInvoicesNewRoute
  '/$orgSlug/journals_/$journalId': typeof OrgSlugJournalsJournalIdRoute
  '/$orgSlug/journals_/new': typeof OrgSlugJournalsNewRoute
  '/$orgSlug/notes/$noteId': typeof OrgSlugNotesNoteIdRoute
  '/$orgSlug/notes_/new': typeof OrgSlugNotesNewRoute
  '/$orgSlug/parties_/$partyId': typeof OrgSlugPartiesPartyIdRouteWithChildren
  '/$orgSlug/payments/$paymentId': typeof OrgSlugPaymentsPaymentIdRoute
  '/$orgSlug/receipts/$receiptId': typeof OrgSlugReceiptsReceiptIdRoute
  '/$orgSlug/reports_/account-ledger': typeof OrgSlugReportsAccountLedgerRoute
  '/$orgSlug/reports_/balance-sheet': typeof OrgSlugReportsBalanceSheetRoute
  '/$orgSlug/reports_/day-book': typeof OrgSlugReportsDayBookRoute
  '/$orgSlug/reports_/profit-and-loss': typeof OrgSlugReportsProfitAndLossRoute
  '/$orgSlug/reports_/trial-balance': typeof OrgSlugReportsTrialBalanceRoute
  '/$orgSlug/settings/audit': typeof OrgSlugSettingsAuditRoute
  '/$orgSlug/settings/files': typeof OrgSlugSettingsFilesRoute
  '/$orgSlug/settings/import': typeof OrgSlugSettingsImportRoute
  '/$orgSlug/settings/locks': typeof OrgSlugSettingsLocksRoute
  '/$orgSlug/settings/members': typeof OrgSlugSettingsMembersRoute
  '/$orgSlug/settings/opening-balance': typeof OrgSlugSettingsOpeningBalanceRoute
  '/$orgSlug/settings/organization': typeof OrgSlugSettingsOrganizationRoute
  '/_site/changelog/$slug': typeof SiteChangelogSlugRoute
  '/$orgSlug/settings/': typeof OrgSlugSettingsIndexRoute
  '/_site/changelog/': typeof SiteChangelogIndexRoute
  '/$orgSlug/bills_/$billId/edit': typeof OrgSlugBillsBillIdEditRoute
  '/$orgSlug/invoices_/$invoiceId/edit': typeof OrgSlugInvoicesInvoiceIdEditRoute
  '/$orgSlug/parties_/$partyId/ledger': typeof OrgSlugPartiesPartyIdLedgerRoute
  '/$orgSlug/parties_/$partyId/transactions': typeof OrgSlugPartiesPartyIdTransactionsRoute
  '/$orgSlug/parties_/$partyId/': typeof OrgSlugPartiesPartyIdIndexRoute
  '/api/$orgSlug/invoices/$invoiceId/pdf': typeof ApiOrgSlugInvoicesInvoiceIdPdfRoute
  '/api/$orgSlug/notes/$noteId/pdf': typeof ApiOrgSlugNotesNoteIdPdfRoute
  '/api/$orgSlug/receipts/$receiptId/pdf': typeof ApiOrgSlugReceiptsReceiptIdPdfRoute
  '/api/$orgSlug/reports/account-ledger/pdf': typeof ApiOrgSlugReportsAccountLedgerPdfRoute
  '/api/$orgSlug/reports/balance-sheet/pdf': typeof ApiOrgSlugReportsBalanceSheetPdfRoute
  '/api/$orgSlug/reports/day-book/pdf': typeof ApiOrgSlugReportsDayBookPdfRoute
  '/api/$orgSlug/reports/profit-and-loss/pdf': typeof ApiOrgSlugReportsProfitAndLossPdfRoute
  '/api/$orgSlug/reports/trial-balance/pdf': typeof ApiOrgSlugReportsTrialBalancePdfRoute
  '/api/$orgSlug/parties/$partyId/statement/pdf': typeof ApiOrgSlugPartiesPartyIdStatementPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$orgSlug'
    | '/'
    | '/create'
    | '/join'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$orgSlug/bills'
    | '/$orgSlug/invoices'
    | '/$orgSlug/notes'
    | '/$orgSlug/parties'
    | '/$orgSlug/payments'
    | '/$orgSlug/receipts'
    | '/$orgSlug/settings'
    | '/$orgSlug/accounts'
    | '/$orgSlug/banking'
    | '/$orgSlug/items'
    | '/$orgSlug/journals'
    | '/$orgSlug/onboarding'
    | '/$orgSlug/reports'
    | '/about'
    | '/billing'
    | '/cas'
    | '/contact'
    | '/customers'
    | '/early-access'
    | '/pricing'
    | '/privacy'
    | '/tally'
    | '/$orgSlug/'
    | '/$orgSlug/bills/$billId'
    | '/$orgSlug/bills/new'
    | '/$orgSlug/invoices/$invoiceId'
    | '/$orgSlug/invoices/new'
    | '/$orgSlug/journals/$journalId'
    | '/$orgSlug/journals/new'
    | '/$orgSlug/notes/$noteId'
    | '/$orgSlug/notes/new'
    | '/$orgSlug/parties/$partyId'
    | '/$orgSlug/payments/$paymentId'
    | '/$orgSlug/receipts/$receiptId'
    | '/$orgSlug/reports/account-ledger'
    | '/$orgSlug/reports/balance-sheet'
    | '/$orgSlug/reports/day-book'
    | '/$orgSlug/reports/profit-and-loss'
    | '/$orgSlug/reports/trial-balance'
    | '/$orgSlug/settings/audit'
    | '/$orgSlug/settings/files'
    | '/$orgSlug/settings/import'
    | '/$orgSlug/settings/locks'
    | '/$orgSlug/settings/members'
    | '/$orgSlug/settings/opening-balance'
    | '/$orgSlug/settings/organization'
    | '/changelog/$slug'
    | '/$orgSlug/settings/'
    | '/changelog/'
    | '/$orgSlug/bills/$billId/edit'
    | '/$orgSlug/invoices/$invoiceId/edit'
    | '/$orgSlug/parties/$partyId/ledger'
    | '/$orgSlug/parties/$partyId/transactions'
    | '/$orgSlug/parties/$partyId/'
    | '/api/$orgSlug/invoices/$invoiceId/pdf'
    | '/api/$orgSlug/notes/$noteId/pdf'
    | '/api/$orgSlug/receipts/$receiptId/pdf'
    | '/api/$orgSlug/reports/account-ledger/pdf'
    | '/api/$orgSlug/reports/balance-sheet/pdf'
    | '/api/$orgSlug/reports/day-book/pdf'
    | '/api/$orgSlug/reports/profit-and-loss/pdf'
    | '/api/$orgSlug/reports/trial-balance/pdf'
    | '/api/$orgSlug/parties/$partyId/statement/pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/create'
    | '/join'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$orgSlug/bills'
    | '/$orgSlug/invoices'
    | '/$orgSlug/notes'
    | '/$orgSlug/parties'
    | '/$orgSlug/payments'
    | '/$orgSlug/receipts'
    | '/$orgSlug/accounts'
    | '/$orgSlug/banking'
    | '/$orgSlug/items'
    | '/$orgSlug/journals'
    | '/$orgSlug/onboarding'
    | '/$orgSlug/reports'
    | '/about'
    | '/billing'
    | '/cas'
    | '/contact'
    | '/customers'
    | '/early-access'
    | '/pricing'
    | '/privacy'
    | '/tally'
    | '/$orgSlug'
    | '/'
    | '/$orgSlug/bills/$billId'
    | '/$orgSlug/bills/new'
    | '/$orgSlug/invoices/$invoiceId'
    | '/$orgSlug/invoices/new'
    | '/$orgSlug/journals/$journalId'
    | '/$orgSlug/journals/new'
    | '/$orgSlug/notes/$noteId'
    | '/$orgSlug/notes/new'
    | '/$orgSlug/payments/$paymentId'
    | '/$orgSlug/receipts/$receiptId'
    | '/$orgSlug/reports/account-ledger'
    | '/$orgSlug/reports/balance-sheet'
    | '/$orgSlug/reports/day-book'
    | '/$orgSlug/reports/profit-and-loss'
    | '/$orgSlug/reports/trial-balance'
    | '/$orgSlug/settings/audit'
    | '/$orgSlug/settings/files'
    | '/$orgSlug/settings/import'
    | '/$orgSlug/settings/locks'
    | '/$orgSlug/settings/members'
    | '/$orgSlug/settings/opening-balance'
    | '/$orgSlug/settings/organization'
    | '/changelog/$slug'
    | '/$orgSlug/settings'
    | '/changelog'
    | '/$orgSlug/bills/$billId/edit'
    | '/$orgSlug/invoices/$invoiceId/edit'
    | '/$orgSlug/parties/$partyId/ledger'
    | '/$orgSlug/parties/$partyId/transactions'
    | '/$orgSlug/parties/$partyId'
    | '/api/$orgSlug/invoices/$invoiceId/pdf'
    | '/api/$orgSlug/notes/$noteId/pdf'
    | '/api/$orgSlug/receipts/$receiptId/pdf'
    | '/api/$orgSlug/reports/account-ledger/pdf'
    | '/api/$orgSlug/reports/balance-sheet/pdf'
    | '/api/$orgSlug/reports/day-book/pdf'
    | '/api/$orgSlug/reports/profit-and-loss/pdf'
    | '/api/$orgSlug/reports/trial-balance/pdf'
    | '/api/$orgSlug/parties/$partyId/statement/pdf'
  id:
    | '__root__'
    | '/$orgSlug'
    | '/_site'
    | '/create'
    | '/join'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$orgSlug/bills'
    | '/$orgSlug/invoices'
    | '/$orgSlug/notes'
    | '/$orgSlug/parties'
    | '/$orgSlug/payments'
    | '/$orgSlug/receipts'
    | '/$orgSlug/settings'
    | '/$orgSlug/accounts'
    | '/$orgSlug/banking'
    | '/$orgSlug/items'
    | '/$orgSlug/journals'
    | '/$orgSlug/onboarding'
    | '/$orgSlug/reports'
    | '/_site/about'
    | '/_site/billing'
    | '/_site/cas'
    | '/_site/contact'
    | '/_site/customers'
    | '/_site/early-access'
    | '/_site/pricing'
    | '/_site/privacy'
    | '/_site/tally'
    | '/$orgSlug/'
    | '/_site/'
    | '/$orgSlug/bills/$billId'
    | '/$orgSlug/bills_/new'
    | '/$orgSlug/invoices/$invoiceId'
    | '/$orgSlug/invoices_/new'
    | '/$orgSlug/journals_/$journalId'
    | '/$orgSlug/journals_/new'
    | '/$orgSlug/notes/$noteId'
    | '/$orgSlug/notes_/new'
    | '/$orgSlug/parties_/$partyId'
    | '/$orgSlug/payments/$paymentId'
    | '/$orgSlug/receipts/$receiptId'
    | '/$orgSlug/reports_/account-ledger'
    | '/$orgSlug/reports_/balance-sheet'
    | '/$orgSlug/reports_/day-book'
    | '/$orgSlug/reports_/profit-and-loss'
    | '/$orgSlug/reports_/trial-balance'
    | '/$orgSlug/settings/audit'
    | '/$orgSlug/settings/files'
    | '/$orgSlug/settings/import'
    | '/$orgSlug/settings/locks'
    | '/$orgSlug/settings/members'
    | '/$orgSlug/settings/opening-balance'
    | '/$orgSlug/settings/organization'
    | '/_site/changelog/$slug'
    | '/$orgSlug/settings/'
    | '/_site/changelog/'
    | '/$orgSlug/bills_/$billId/edit'
    | '/$orgSlug/invoices_/$invoiceId/edit'
    | '/$orgSlug/parties_/$partyId/ledger'
    | '/$orgSlug/parties_/$partyId/transactions'
    | '/$orgSlug/parties_/$partyId/'
    | '/api/$orgSlug/invoices/$invoiceId/pdf'
    | '/api/$orgSlug/notes/$noteId/pdf'
    | '/api/$orgSlug/receipts/$receiptId/pdf'
    | '/api/$orgSlug/reports/account-ledger/pdf'
    | '/api/$orgSlug/reports/balance-sheet/pdf'
    | '/api/$orgSlug/reports/day-book/pdf'
    | '/api/$orgSlug/reports/profit-and-loss/pdf'
    | '/api/$orgSlug/reports/trial-balance/pdf'
    | '/api/$orgSlug/parties/$partyId/statement/pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  OrgSlugRouteRoute: typeof OrgSlugRouteRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
  CreateRoute: typeof CreateRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiOrgSlugInvoicesInvoiceIdPdfRoute: typeof ApiOrgSlugInvoicesInvoiceIdPdfRoute
  ApiOrgSlugNotesNoteIdPdfRoute: typeof ApiOrgSlugNotesNoteIdPdfRoute
  ApiOrgSlugReceiptsReceiptIdPdfRoute: typeof ApiOrgSlugReceiptsReceiptIdPdfRoute
  ApiOrgSlugReportsAccountLedgerPdfRoute: typeof ApiOrgSlugReportsAccountLedgerPdfRoute
  ApiOrgSlugReportsBalanceSheetPdfRoute: typeof ApiOrgSlugReportsBalanceSheetPdfRoute
  ApiOrgSlugReportsDayBookPdfRoute: typeof ApiOrgSlugReportsDayBookPdfRoute
  ApiOrgSlugReportsProfitAndLossPdfRoute: typeof ApiOrgSlugReportsProfitAndLossPdfRoute
  ApiOrgSlugReportsTrialBalancePdfRoute: typeof ApiOrgSlugReportsTrialBalancePdfRoute
  ApiOrgSlugPartiesPartyIdStatementPdfRoute: typeof ApiOrgSlugPartiesPartyIdStatementPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$orgSlug': {
      id: '/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof OrgSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/': {
      id: '/$orgSlug/'
      path: '/'
      fullPath: '/$orgSlug/'
      preLoaderRoute: typeof OrgSlugIndexRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/accounts': {
      id: '/$orgSlug/accounts'
      path: '/accounts'
      fullPath: '/$orgSlug/accounts'
      preLoaderRoute: typeof OrgSlugAccountsRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/banking': {
      id: '/$orgSlug/banking'
      path: '/banking'
      fullPath: '/$orgSlug/banking'
      preLoaderRoute: typeof OrgSlugBankingRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/bills': {
      id: '/$orgSlug/bills'
      path: '/bills'
      fullPath: '/$orgSlug/bills'
      preLoaderRoute: typeof OrgSlugBillsRouteRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/invoices': {
      id: '/$orgSlug/invoices'
      path: '/invoices'
      fullPath: '/$orgSlug/invoices'
      preLoaderRoute: typeof OrgSlugInvoicesRouteRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/items': {
      id: '/$orgSlug/items'
      path: '/items'
      fullPath: '/$orgSlug/items'
      preLoaderRoute: typeof OrgSlugItemsRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/journals': {
      id: '/$orgSlug/journals'
      path: '/journals'
      fullPath: '/$orgSlug/journals'
      preLoaderRoute: typeof OrgSlugJournalsRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/notes': {
      id: '/$orgSlug/notes'
      path: '/notes'
      fullPath: '/$orgSlug/notes'
      preLoaderRoute: typeof OrgSlugNotesRouteRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/onboarding': {
      id: '/$orgSlug/onboarding'
      path: '/onboarding'
      fullPath: '/$orgSlug/onboarding'
      preLoaderRoute: typeof OrgSlugOnboardingRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/parties': {
      id: '/$orgSlug/parties'
      path: '/parties'
      fullPath: '/$orgSlug/parties'
      preLoaderRoute: typeof OrgSlugPartiesRouteRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/payments': {
      id: '/$orgSlug/payments'
      path: '/payments'
      fullPath: '/$orgSlug/payments'
      preLoaderRoute: typeof OrgSlugPaymentsRouteRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/receipts': {
      id: '/$orgSlug/receipts'
      path: '/receipts'
      fullPath: '/$orgSlug/receipts'
      preLoaderRoute: typeof OrgSlugReceiptsRouteRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/reports': {
      id: '/$orgSlug/reports'
      path: '/reports'
      fullPath: '/$orgSlug/reports'
      preLoaderRoute: typeof OrgSlugReportsRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/settings': {
      id: '/$orgSlug/settings'
      path: '/settings'
      fullPath: '/$orgSlug/settings'
      preLoaderRoute: typeof OrgSlugSettingsRouteRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/billing': {
      id: '/_site/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof SiteBillingRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/cas': {
      id: '/_site/cas'
      path: '/cas'
      fullPath: '/cas'
      preLoaderRoute: typeof SiteCasRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/customers': {
      id: '/_site/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof SiteCustomersRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/early-access': {
      id: '/_site/early-access'
      path: '/early-access'
      fullPath: '/early-access'
      preLoaderRoute: typeof SiteEarlyAccessRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/pricing': {
      id: '/_site/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof SitePricingRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/privacy': {
      id: '/_site/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof SitePrivacyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/tally': {
      id: '/_site/tally'
      path: '/tally'
      fullPath: '/tally'
      preLoaderRoute: typeof SiteTallyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/$orgSlug/bills/$billId': {
      id: '/$orgSlug/bills/$billId'
      path: '/$billId'
      fullPath: '/$orgSlug/bills/$billId'
      preLoaderRoute: typeof OrgSlugBillsBillIdRouteImport
      parentRoute: typeof OrgSlugBillsRouteRoute
    }
    '/$orgSlug/bills_/new': {
      id: '/$orgSlug/bills_/new'
      path: '/bills/new'
      fullPath: '/$orgSlug/bills/new'
      preLoaderRoute: typeof OrgSlugBillsNewRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/invoices/$invoiceId': {
      id: '/$orgSlug/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/$orgSlug/invoices/$invoiceId'
      preLoaderRoute: typeof OrgSlugInvoicesInvoiceIdRouteImport
      parentRoute: typeof OrgSlugInvoicesRouteRoute
    }
    '/$orgSlug/invoices_/new': {
      id: '/$orgSlug/invoices_/new'
      path: '/invoices/new'
      fullPath: '/$orgSlug/invoices/new'
      preLoaderRoute: typeof OrgSlugInvoicesNewRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/journals_/$journalId': {
      id: '/$orgSlug/journals_/$journalId'
      path: '/journals/$journalId'
      fullPath: '/$orgSlug/journals/$journalId'
      preLoaderRoute: typeof OrgSlugJournalsJournalIdRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/journals_/new': {
      id: '/$orgSlug/journals_/new'
      path: '/journals/new'
      fullPath: '/$orgSlug/journals/new'
      preLoaderRoute: typeof OrgSlugJournalsNewRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/notes/$noteId': {
      id: '/$orgSlug/notes/$noteId'
      path: '/$noteId'
      fullPath: '/$orgSlug/notes/$noteId'
      preLoaderRoute: typeof OrgSlugNotesNoteIdRouteImport
      parentRoute: typeof OrgSlugNotesRouteRoute
    }
    '/$orgSlug/notes_/new': {
      id: '/$orgSlug/notes_/new'
      path: '/notes/new'
      fullPath: '/$orgSlug/notes/new'
      preLoaderRoute: typeof OrgSlugNotesNewRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/parties_/$partyId': {
      id: '/$orgSlug/parties_/$partyId'
      path: '/parties/$partyId'
      fullPath: '/$orgSlug/parties/$partyId'
      preLoaderRoute: typeof OrgSlugPartiesPartyIdRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/payments/$paymentId': {
      id: '/$orgSlug/payments/$paymentId'
      path: '/$paymentId'
      fullPath: '/$orgSlug/payments/$paymentId'
      preLoaderRoute: typeof OrgSlugPaymentsPaymentIdRouteImport
      parentRoute: typeof OrgSlugPaymentsRouteRoute
    }
    '/$orgSlug/receipts/$receiptId': {
      id: '/$orgSlug/receipts/$receiptId'
      path: '/$receiptId'
      fullPath: '/$orgSlug/receipts/$receiptId'
      preLoaderRoute: typeof OrgSlugReceiptsReceiptIdRouteImport
      parentRoute: typeof OrgSlugReceiptsRouteRoute
    }
    '/$orgSlug/reports_/account-ledger': {
      id: '/$orgSlug/reports_/account-ledger'
      path: '/reports/account-ledger'
      fullPath: '/$orgSlug/reports/account-ledger'
      preLoaderRoute: typeof OrgSlugReportsAccountLedgerRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/reports_/balance-sheet': {
      id: '/$orgSlug/reports_/balance-sheet'
      path: '/reports/balance-sheet'
      fullPath: '/$orgSlug/reports/balance-sheet'
      preLoaderRoute: typeof OrgSlugReportsBalanceSheetRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/reports_/day-book': {
      id: '/$orgSlug/reports_/day-book'
      path: '/reports/day-book'
      fullPath: '/$orgSlug/reports/day-book'
      preLoaderRoute: typeof OrgSlugReportsDayBookRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/reports_/profit-and-loss': {
      id: '/$orgSlug/reports_/profit-and-loss'
      path: '/reports/profit-and-loss'
      fullPath: '/$orgSlug/reports/profit-and-loss'
      preLoaderRoute: typeof OrgSlugReportsProfitAndLossRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/reports_/trial-balance': {
      id: '/$orgSlug/reports_/trial-balance'
      path: '/reports/trial-balance'
      fullPath: '/$orgSlug/reports/trial-balance'
      preLoaderRoute: typeof OrgSlugReportsTrialBalanceRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/settings/': {
      id: '/$orgSlug/settings/'
      path: '/'
      fullPath: '/$orgSlug/settings/'
      preLoaderRoute: typeof OrgSlugSettingsIndexRouteImport
      parentRoute: typeof OrgSlugSettingsRouteRoute
    }
    '/$orgSlug/settings/audit': {
      id: '/$orgSlug/settings/audit'
      path: '/audit'
      fullPath: '/$orgSlug/settings/audit'
      preLoaderRoute: typeof OrgSlugSettingsAuditRouteImport
      parentRoute: typeof OrgSlugSettingsRouteRoute
    }
    '/$orgSlug/settings/files': {
      id: '/$orgSlug/settings/files'
      path: '/files'
      fullPath: '/$orgSlug/settings/files'
      preLoaderRoute: typeof OrgSlugSettingsFilesRouteImport
      parentRoute: typeof OrgSlugSettingsRouteRoute
    }
    '/$orgSlug/settings/import': {
      id: '/$orgSlug/settings/import'
      path: '/import'
      fullPath: '/$orgSlug/settings/import'
      preLoaderRoute: typeof OrgSlugSettingsImportRouteImport
      parentRoute: typeof OrgSlugSettingsRouteRoute
    }
    '/$orgSlug/settings/locks': {
      id: '/$orgSlug/settings/locks'
      path: '/locks'
      fullPath: '/$orgSlug/settings/locks'
      preLoaderRoute: typeof OrgSlugSettingsLocksRouteImport
      parentRoute: typeof OrgSlugSettingsRouteRoute
    }
    '/$orgSlug/settings/members': {
      id: '/$orgSlug/settings/members'
      path: '/members'
      fullPath: '/$orgSlug/settings/members'
      preLoaderRoute: typeof OrgSlugSettingsMembersRouteImport
      parentRoute: typeof OrgSlugSettingsRouteRoute
    }
    '/$orgSlug/settings/opening-balance': {
      id: '/$orgSlug/settings/opening-balance'
      path: '/opening-balance'
      fullPath: '/$orgSlug/settings/opening-balance'
      preLoaderRoute: typeof OrgSlugSettingsOpeningBalanceRouteImport
      parentRoute: typeof OrgSlugSettingsRouteRoute
    }
    '/$orgSlug/settings/organization': {
      id: '/$orgSlug/settings/organization'
      path: '/organization'
      fullPath: '/$orgSlug/settings/organization'
      preLoaderRoute: typeof OrgSlugSettingsOrganizationRouteImport
      parentRoute: typeof OrgSlugSettingsRouteRoute
    }
    '/_site/changelog/': {
      id: '/_site/changelog/'
      path: '/changelog'
      fullPath: '/changelog/'
      preLoaderRoute: typeof SiteChangelogIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/changelog/$slug': {
      id: '/_site/changelog/$slug'
      path: '/changelog/$slug'
      fullPath: '/changelog/$slug'
      preLoaderRoute: typeof SiteChangelogSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/$orgSlug/bills_/$billId/edit': {
      id: '/$orgSlug/bills_/$billId/edit'
      path: '/bills/$billId/edit'
      fullPath: '/$orgSlug/bills/$billId/edit'
      preLoaderRoute: typeof OrgSlugBillsBillIdEditRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/invoices_/$invoiceId/edit': {
      id: '/$orgSlug/invoices_/$invoiceId/edit'
      path: '/invoices/$invoiceId/edit'
      fullPath: '/$orgSlug/invoices/$invoiceId/edit'
      preLoaderRoute: typeof OrgSlugInvoicesInvoiceIdEditRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/parties_/$partyId/': {
      id: '/$orgSlug/parties_/$partyId/'
      path: '/'
      fullPath: '/$orgSlug/parties/$partyId/'
      preLoaderRoute: typeof OrgSlugPartiesPartyIdIndexRouteImport
      parentRoute: typeof OrgSlugPartiesPartyIdRoute
    }
    '/$orgSlug/parties_/$partyId/ledger': {
      id: '/$orgSlug/parties_/$partyId/ledger'
      path: '/ledger'
      fullPath: '/$orgSlug/parties/$partyId/ledger'
      preLoaderRoute: typeof OrgSlugPartiesPartyIdLedgerRouteImport
      parentRoute: typeof OrgSlugPartiesPartyIdRoute
    }
    '/$orgSlug/parties_/$partyId/transactions': {
      id: '/$orgSlug/parties_/$partyId/transactions'
      path: '/transactions'
      fullPath: '/$orgSlug/parties/$partyId/transactions'
      preLoaderRoute: typeof OrgSlugPartiesPartyIdTransactionsRouteImport
      parentRoute: typeof OrgSlugPartiesPartyIdRoute
    }
    '/api/$orgSlug/invoices/$invoiceId/pdf': {
      id: '/api/$orgSlug/invoices/$invoiceId/pdf'
      path: '/api/$orgSlug/invoices/$invoiceId/pdf'
      fullPath: '/api/$orgSlug/invoices/$invoiceId/pdf'
      preLoaderRoute: typeof ApiOrgSlugInvoicesInvoiceIdPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/notes/$noteId/pdf': {
      id: '/api/$orgSlug/notes/$noteId/pdf'
      path: '/api/$orgSlug/notes/$noteId/pdf'
      fullPath: '/api/$orgSlug/notes/$noteId/pdf'
      preLoaderRoute: typeof ApiOrgSlugNotesNoteIdPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/receipts/$receiptId/pdf': {
      id: '/api/$orgSlug/receipts/$receiptId/pdf'
      path: '/api/$orgSlug/receipts/$receiptId/pdf'
      fullPath: '/api/$orgSlug/receipts/$receiptId/pdf'
      preLoaderRoute: typeof ApiOrgSlugReceiptsReceiptIdPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/reports/account-ledger/pdf': {
      id: '/api/$orgSlug/reports/account-ledger/pdf'
      path: '/api/$orgSlug/reports/account-ledger/pdf'
      fullPath: '/api/$orgSlug/reports/account-ledger/pdf'
      preLoaderRoute: typeof ApiOrgSlugReportsAccountLedgerPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/reports/balance-sheet/pdf': {
      id: '/api/$orgSlug/reports/balance-sheet/pdf'
      path: '/api/$orgSlug/reports/balance-sheet/pdf'
      fullPath: '/api/$orgSlug/reports/balance-sheet/pdf'
      preLoaderRoute: typeof ApiOrgSlugReportsBalanceSheetPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/reports/day-book/pdf': {
      id: '/api/$orgSlug/reports/day-book/pdf'
      path: '/api/$orgSlug/reports/day-book/pdf'
      fullPath: '/api/$orgSlug/reports/day-book/pdf'
      preLoaderRoute: typeof ApiOrgSlugReportsDayBookPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/reports/profit-and-loss/pdf': {
      id: '/api/$orgSlug/reports/profit-and-loss/pdf'
      path: '/api/$orgSlug/reports/profit-and-loss/pdf'
      fullPath: '/api/$orgSlug/reports/profit-and-loss/pdf'
      preLoaderRoute: typeof ApiOrgSlugReportsProfitAndLossPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/reports/trial-balance/pdf': {
      id: '/api/$orgSlug/reports/trial-balance/pdf'
      path: '/api/$orgSlug/reports/trial-balance/pdf'
      fullPath: '/api/$orgSlug/reports/trial-balance/pdf'
      preLoaderRoute: typeof ApiOrgSlugReportsTrialBalancePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$orgSlug/parties/$partyId/statement/pdf': {
      id: '/api/$orgSlug/parties/$partyId/statement/pdf'
      path: '/api/$orgSlug/parties/$partyId/statement/pdf'
      fullPath: '/api/$orgSlug/parties/$partyId/statement/pdf'
      preLoaderRoute: typeof ApiOrgSlugPartiesPartyIdStatementPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OrgSlugBillsRouteRouteChildren {
  OrgSlugBillsBillIdRoute: typeof OrgSlugBillsBillIdRoute
}

const OrgSlugBillsRouteRouteChildren: OrgSlugBillsRouteRouteChildren = {
  OrgSlugBillsBillIdRoute: OrgSlugBillsBillIdRoute,
}

const OrgSlugBillsRouteRouteWithChildren =
  OrgSlugBillsRouteRoute._addFileChildren(OrgSlugBillsRouteRouteChildren)

interface OrgSlugInvoicesRouteRouteChildren {
  OrgSlugInvoicesInvoiceIdRoute: typeof OrgSlugInvoicesInvoiceIdRoute
}

const OrgSlugInvoicesRouteRouteChildren: OrgSlugInvoicesRouteRouteChildren = {
  OrgSlugInvoicesInvoiceIdRoute: OrgSlugInvoicesInvoiceIdRoute,
}

const OrgSlugInvoicesRouteRouteWithChildren =
  OrgSlugInvoicesRouteRoute._addFileChildren(OrgSlugInvoicesRouteRouteChildren)

interface OrgSlugNotesRouteRouteChildren {
  OrgSlugNotesNoteIdRoute: typeof OrgSlugNotesNoteIdRoute
}

const OrgSlugNotesRouteRouteChildren: OrgSlugNotesRouteRouteChildren = {
  OrgSlugNotesNoteIdRoute: OrgSlugNotesNoteIdRoute,
}

const OrgSlugNotesRouteRouteWithChildren =
  OrgSlugNotesRouteRoute._addFileChildren(OrgSlugNotesRouteRouteChildren)

interface OrgSlugPaymentsRouteRouteChildren {
  OrgSlugPaymentsPaymentIdRoute: typeof OrgSlugPaymentsPaymentIdRoute
}

const OrgSlugPaymentsRouteRouteChildren: OrgSlugPaymentsRouteRouteChildren = {
  OrgSlugPaymentsPaymentIdRoute: OrgSlugPaymentsPaymentIdRoute,
}

const OrgSlugPaymentsRouteRouteWithChildren =
  OrgSlugPaymentsRouteRoute._addFileChildren(OrgSlugPaymentsRouteRouteChildren)

interface OrgSlugReceiptsRouteRouteChildren {
  OrgSlugReceiptsReceiptIdRoute: typeof OrgSlugReceiptsReceiptIdRoute
}

const OrgSlugReceiptsRouteRouteChildren: OrgSlugReceiptsRouteRouteChildren = {
  OrgSlugReceiptsReceiptIdRoute: OrgSlugReceiptsReceiptIdRoute,
}

const OrgSlugReceiptsRouteRouteWithChildren =
  OrgSlugReceiptsRouteRoute._addFileChildren(OrgSlugReceiptsRouteRouteChildren)

interface OrgSlugSettingsRouteRouteChildren {
  OrgSlugSettingsAuditRoute: typeof OrgSlugSettingsAuditRoute
  OrgSlugSettingsFilesRoute: typeof OrgSlugSettingsFilesRoute
  OrgSlugSettingsImportRoute: typeof OrgSlugSettingsImportRoute
  OrgSlugSettingsLocksRoute: typeof OrgSlugSettingsLocksRoute
  OrgSlugSettingsMembersRoute: typeof OrgSlugSettingsMembersRoute
  OrgSlugSettingsOpeningBalanceRoute: typeof OrgSlugSettingsOpeningBalanceRoute
  OrgSlugSettingsOrganizationRoute: typeof OrgSlugSettingsOrganizationRoute
  OrgSlugSettingsIndexRoute: typeof OrgSlugSettingsIndexRoute
}

const OrgSlugSettingsRouteRouteChildren: OrgSlugSettingsRouteRouteChildren = {
  OrgSlugSettingsAuditRoute: OrgSlugSettingsAuditRoute,
  OrgSlugSettingsFilesRoute: OrgSlugSettingsFilesRoute,
  OrgSlugSettingsImportRoute: OrgSlugSettingsImportRoute,
  OrgSlugSettingsLocksRoute: OrgSlugSettingsLocksRoute,
  OrgSlugSettingsMembersRoute: OrgSlugSettingsMembersRoute,
  OrgSlugSettingsOpeningBalanceRoute: OrgSlugSettingsOpeningBalanceRoute,
  OrgSlugSettingsOrganizationRoute: OrgSlugSettingsOrganizationRoute,
  OrgSlugSettingsIndexRoute: OrgSlugSettingsIndexRoute,
}

const OrgSlugSettingsRouteRouteWithChildren =
  OrgSlugSettingsRouteRoute._addFileChildren(OrgSlugSettingsRouteRouteChildren)

interface OrgSlugPartiesPartyIdRouteChildren {
  OrgSlugPartiesPartyIdLedgerRoute: typeof OrgSlugPartiesPartyIdLedgerRoute
  OrgSlugPartiesPartyIdTransactionsRoute: typeof OrgSlugPartiesPartyIdTransactionsRoute
  OrgSlugPartiesPartyIdIndexRoute: typeof OrgSlugPartiesPartyIdIndexRoute
}

const OrgSlugPartiesPartyIdRouteChildren: OrgSlugPartiesPartyIdRouteChildren = {
  OrgSlugPartiesPartyIdLedgerRoute: OrgSlugPartiesPartyIdLedgerRoute,
  OrgSlugPartiesPartyIdTransactionsRoute:
    OrgSlugPartiesPartyIdTransactionsRoute,
  OrgSlugPartiesPartyIdIndexRoute: OrgSlugPartiesPartyIdIndexRoute,
}

const OrgSlugPartiesPartyIdRouteWithChildren =
  OrgSlugPartiesPartyIdRoute._addFileChildren(
    OrgSlugPartiesPartyIdRouteChildren,
  )

interface OrgSlugRouteRouteChildren {
  OrgSlugBillsRouteRoute: typeof OrgSlugBillsRouteRouteWithChildren
  OrgSlugInvoicesRouteRoute: typeof OrgSlugInvoicesRouteRouteWithChildren
  OrgSlugNotesRouteRoute: typeof OrgSlugNotesRouteRouteWithChildren
  OrgSlugPartiesRouteRoute: typeof OrgSlugPartiesRouteRoute
  OrgSlugPaymentsRouteRoute: typeof OrgSlugPaymentsRouteRouteWithChildren
  OrgSlugReceiptsRouteRoute: typeof OrgSlugReceiptsRouteRouteWithChildren
  OrgSlugSettingsRouteRoute: typeof OrgSlugSettingsRouteRouteWithChildren
  OrgSlugAccountsRoute: typeof OrgSlugAccountsRoute
  OrgSlugBankingRoute: typeof OrgSlugBankingRoute
  OrgSlugItemsRoute: typeof OrgSlugItemsRoute
  OrgSlugJournalsRoute: typeof OrgSlugJournalsRoute
  OrgSlugOnboardingRoute: typeof OrgSlugOnboardingRoute
  OrgSlugReportsRoute: typeof OrgSlugReportsRoute
  OrgSlugIndexRoute: typeof OrgSlugIndexRoute
  OrgSlugBillsNewRoute: typeof OrgSlugBillsNewRoute
  OrgSlugInvoicesNewRoute: typeof OrgSlugInvoicesNewRoute
  OrgSlugJournalsJournalIdRoute: typeof OrgSlugJournalsJournalIdRoute
  OrgSlugJournalsNewRoute: typeof OrgSlugJournalsNewRoute
  OrgSlugNotesNewRoute: typeof OrgSlugNotesNewRoute
  OrgSlugPartiesPartyIdRoute: typeof OrgSlugPartiesPartyIdRouteWithChildren
  OrgSlugReportsAccountLedgerRoute: typeof OrgSlugReportsAccountLedgerRoute
  OrgSlugReportsBalanceSheetRoute: typeof OrgSlugReportsBalanceSheetRoute
  OrgSlugReportsDayBookRoute: typeof OrgSlugReportsDayBookRoute
  OrgSlugReportsProfitAndLossRoute: typeof OrgSlugReportsProfitAndLossRoute
  OrgSlugReportsTrialBalanceRoute: typeof OrgSlugReportsTrialBalanceRoute
  OrgSlugBillsBillIdEditRoute: typeof OrgSlugBillsBillIdEditRoute
  OrgSlugInvoicesInvoiceIdEditRoute: typeof OrgSlugInvoicesInvoiceIdEditRoute
}

const OrgSlugRouteRouteChildren: OrgSlugRouteRouteChildren = {
  OrgSlugBillsRouteRoute: OrgSlugBillsRouteRouteWithChildren,
  OrgSlugInvoicesRouteRoute: OrgSlugInvoicesRouteRouteWithChildren,
  OrgSlugNotesRouteRoute: OrgSlugNotesRouteRouteWithChildren,
  OrgSlugPartiesRouteRoute: OrgSlugPartiesRouteRoute,
  OrgSlugPaymentsRouteRoute: OrgSlugPaymentsRouteRouteWithChildren,
  OrgSlugReceiptsRouteRoute: OrgSlugReceiptsRouteRouteWithChildren,
  OrgSlugSettingsRouteRoute: OrgSlugSettingsRouteRouteWithChildren,
  OrgSlugAccountsRoute: OrgSlugAccountsRoute,
  OrgSlugBankingRoute: OrgSlugBankingRoute,
  OrgSlugItemsRoute: OrgSlugItemsRoute,
  OrgSlugJournalsRoute: OrgSlugJournalsRoute,
  OrgSlugOnboardingRoute: OrgSlugOnboardingRoute,
  OrgSlugReportsRoute: OrgSlugReportsRoute,
  OrgSlugIndexRoute: OrgSlugIndexRoute,
  OrgSlugBillsNewRoute: OrgSlugBillsNewRoute,
  OrgSlugInvoicesNewRoute: OrgSlugInvoicesNewRoute,
  OrgSlugJournalsJournalIdRoute: OrgSlugJournalsJournalIdRoute,
  OrgSlugJournalsNewRoute: OrgSlugJournalsNewRoute,
  OrgSlugNotesNewRoute: OrgSlugNotesNewRoute,
  OrgSlugPartiesPartyIdRoute: OrgSlugPartiesPartyIdRouteWithChildren,
  OrgSlugReportsAccountLedgerRoute: OrgSlugReportsAccountLedgerRoute,
  OrgSlugReportsBalanceSheetRoute: OrgSlugReportsBalanceSheetRoute,
  OrgSlugReportsDayBookRoute: OrgSlugReportsDayBookRoute,
  OrgSlugReportsProfitAndLossRoute: OrgSlugReportsProfitAndLossRoute,
  OrgSlugReportsTrialBalanceRoute: OrgSlugReportsTrialBalanceRoute,
  OrgSlugBillsBillIdEditRoute: OrgSlugBillsBillIdEditRoute,
  OrgSlugInvoicesInvoiceIdEditRoute: OrgSlugInvoicesInvoiceIdEditRoute,
}

const OrgSlugRouteRouteWithChildren = OrgSlugRouteRoute._addFileChildren(
  OrgSlugRouteRouteChildren,
)

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteBillingRoute: typeof SiteBillingRoute
  SiteCasRoute: typeof SiteCasRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteCustomersRoute: typeof SiteCustomersRoute
  SiteEarlyAccessRoute: typeof SiteEarlyAccessRoute
  SitePricingRoute: typeof SitePricingRoute
  SitePrivacyRoute: typeof SitePrivacyRoute
  SiteTallyRoute: typeof SiteTallyRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteChangelogSlugRoute: typeof SiteChangelogSlugRoute
  SiteChangelogIndexRoute: typeof SiteChangelogIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteBillingRoute: SiteBillingRoute,
  SiteCasRoute: SiteCasRoute,
  SiteContactRoute: SiteContactRoute,
  SiteCustomersRoute: SiteCustomersRoute,
  SiteEarlyAccessRoute: SiteEarlyAccessRoute,
  SitePricingRoute: SitePricingRoute,
  SitePrivacyRoute: SitePrivacyRoute,
  SiteTallyRoute: SiteTallyRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteChangelogSlugRoute: SiteChangelogSlugRoute,
  SiteChangelogIndexRoute: SiteChangelogIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  OrgSlugRouteRoute: OrgSlugRouteRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
  CreateRoute: CreateRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiOrgSlugInvoicesInvoiceIdPdfRoute: ApiOrgSlugInvoicesInvoiceIdPdfRoute,
  ApiOrgSlugNotesNoteIdPdfRoute: ApiOrgSlugNotesNoteIdPdfRoute,
  ApiOrgSlugReceiptsReceiptIdPdfRoute: ApiOrgSlugReceiptsReceiptIdPdfRoute,
  ApiOrgSlugReportsAccountLedgerPdfRoute:
    ApiOrgSlugReportsAccountLedgerPdfRoute,
  ApiOrgSlugReportsBalanceSheetPdfRoute: ApiOrgSlugReportsBalanceSheetPdfRoute,
  ApiOrgSlugReportsDayBookPdfRoute: ApiOrgSlugReportsDayBookPdfRoute,
  ApiOrgSlugReportsProfitAndLossPdfRoute:
    ApiOrgSlugReportsProfitAndLossPdfRoute,
  ApiOrgSlugReportsTrialBalancePdfRoute: ApiOrgSlugReportsTrialBalancePdfRoute,
  ApiOrgSlugPartiesPartyIdStatementPdfRoute:
    ApiOrgSlugPartiesPartyIdStatementPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
