/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgSlugRouteRouteImport } from './routes/$orgSlug/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CreateRouteImport } from './routes/create'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OrgSlugIndexRouteImport } from './routes/$orgSlug/index'
import { Route as OrgSlugFilesRouteImport } from './routes/$orgSlug/files'
import { Route as OrgSlugOnboardingRouteImport } from './routes/$orgSlug/onboarding'
import { Route as OrgSlugPartiesRouteRouteImport } from './routes/$orgSlug/parties/route'
import { Route as OrgSlugReceiptsRouteRouteImport } from './routes/$orgSlug/receipts/route'
import { Route as OrgSlugSettingsRouteRouteImport } from './routes/$orgSlug/settings/route'
import { Route as ChangelogIndexRouteImport } from './routes/changelog.index'
import { Route as ChangelogSlugRouteImport } from './routes/changelog.$slug'
import { Route as OrgSlugPartiesPartyIdRouteImport } from './routes/$orgSlug/parties_.$partyId'
import { Route as OrgSlugReceiptsReceiptIdRouteImport } from './routes/$orgSlug/receipts/$receiptId'
import { Route as OrgSlugSettingsIndexRouteImport } from './routes/$orgSlug/settings/index'
import { Route as OrgSlugSettingsAuditRouteImport } from './routes/$orgSlug/settings/audit'
import { Route as OrgSlugSettingsBanksRouteImport } from './routes/$orgSlug/settings/banks'
import { Route as OrgSlugSettingsMembersRouteImport } from './routes/$orgSlug/settings/members'
import { Route as OrgSlugSettingsOrganizationRouteImport } from './routes/$orgSlug/settings/organization'
import { Route as OrgSlugPartiesPartyIdIndexRouteImport } from './routes/$orgSlug/parties_.$partyId.index'
import { Route as OrgSlugPartiesPartyIdLedgerRouteImport } from './routes/$orgSlug/parties_.$partyId.ledger'
import { Route as OrgSlugPartiesPartyIdReceiptsRouteImport } from './routes/$orgSlug/parties_.$partyId.receipts'
import { Route as ApiOrgSlugReceiptsReceiptIdPdfRouteImport } from './routes/api.$orgSlug.receipts.$receiptId.pdf'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugRouteRoute = OrgSlugRouteRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugIndexRoute = OrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugFilesRoute = OrgSlugFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugOnboardingRoute = OrgSlugOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugPartiesRouteRoute = OrgSlugPartiesRouteRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugReceiptsRouteRoute = OrgSlugReceiptsRouteRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugSettingsRouteRoute = OrgSlugSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const ChangelogIndexRoute = ChangelogIndexRouteImport.update({
  id: '/changelog/',
  path: '/changelog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogSlugRoute = ChangelogSlugRouteImport.update({
  id: '/changelog/$slug',
  path: '/changelog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugPartiesPartyIdRoute = OrgSlugPartiesPartyIdRouteImport.update({
  id: '/parties_/$partyId',
  path: '/parties/$partyId',
  getParentRoute: () => OrgSlugRouteRoute,
} as any)
const OrgSlugReceiptsReceiptIdRoute =
  OrgSlugReceiptsReceiptIdRouteImport.update({
    id: '/$receiptId',
    path: '/$receiptId',
    getParentRoute: () => OrgSlugReceiptsRouteRoute,
  } as any)
const OrgSlugSettingsIndexRoute = OrgSlugSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgSlugSettingsRouteRoute,
} as any)
const OrgSlugSettingsAuditRoute = OrgSlugSettingsAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => OrgSlugSettingsRouteRoute,
} as any)
const OrgSlugSettingsBanksRoute = OrgSlugSettingsBanksRouteImport.update({
  id: '/banks',
  path: '/banks',
  getParentRoute: () => OrgSlugSettingsRouteRoute,
} as any)
const OrgSlugSettingsMembersRoute = OrgSlugSettingsMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => OrgSlugSettingsRouteRoute,
} as any)
const OrgSlugSettingsOrganizationRoute =
  OrgSlugSettingsOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => OrgSlugSettingsRouteRoute,
  } as any)
const OrgSlugPartiesPartyIdIndexRoute =
  OrgSlugPartiesPartyIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrgSlugPartiesPartyIdRoute,
  } as any)
const OrgSlugPartiesPartyIdLedgerRoute =
  OrgSlugPartiesPartyIdLedgerRouteImport.update({
    id: '/ledger',
    path: '/ledger',
    getParentRoute: () => OrgSlugPartiesPartyIdRoute,
  } as any)
const OrgSlugPartiesPartyIdReceiptsRoute =
  OrgSlugPartiesPartyIdReceiptsRouteImport.update({
    id: '/receipts',
    path: '/receipts',
    getParentRoute: () => OrgSlugPartiesPartyIdRoute,
  } as any)
const ApiOrgSlugReceiptsReceiptIdPdfRoute =
  ApiOrgSlugReceiptsReceiptIdPdfRouteImport.update({
    id: '/api/$orgSlug/receipts/$receiptId/pdf',
    path: '/api/$orgSlug/receipts/$receiptId/pdf',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/billing': typeof BillingRoute
  '/contact': typeof ContactRoute
  '/create': typeof CreateRoute
  '/customers': typeof CustomersRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$orgSlug/parties': typeof OrgSlugPartiesRouteRoute
  '/$orgSlug/receipts': typeof OrgSlugReceiptsRouteRouteWithChildren
  '/$orgSlug/settings': typeof OrgSlugSettingsRouteRouteWithChildren
  '/$orgSlug/files': typeof OrgSlugFilesRoute
  '/$orgSlug/onboarding': typeof OrgSlugOnboardingRoute
  '/changelog/$slug': typeof ChangelogSlugRoute
  '/$orgSlug/': typeof OrgSlugIndexRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/$orgSlug/parties/$partyId': typeof OrgSlugPartiesPartyIdRouteWithChildren
  '/$orgSlug/receipts/$receiptId': typeof OrgSlugReceiptsReceiptIdRoute
  '/$orgSlug/settings/audit': typeof OrgSlugSettingsAuditRoute
  '/$orgSlug/settings/banks': typeof OrgSlugSettingsBanksRoute
  '/$orgSlug/settings/members': typeof OrgSlugSettingsMembersRoute
  '/$orgSlug/settings/organization': typeof OrgSlugSettingsOrganizationRoute
  '/$orgSlug/settings/': typeof OrgSlugSettingsIndexRoute
  '/$orgSlug/parties/$partyId/ledger': typeof OrgSlugPartiesPartyIdLedgerRoute
  '/$orgSlug/parties/$partyId/receipts': typeof OrgSlugPartiesPartyIdReceiptsRoute
  '/$orgSlug/parties/$partyId/': typeof OrgSlugPartiesPartyIdIndexRoute
  '/api/$orgSlug/receipts/$receiptId/pdf': typeof ApiOrgSlugReceiptsReceiptIdPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/billing': typeof BillingRoute
  '/contact': typeof ContactRoute
  '/create': typeof CreateRoute
  '/customers': typeof CustomersRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$orgSlug/parties': typeof OrgSlugPartiesRouteRoute
  '/$orgSlug/receipts': typeof OrgSlugReceiptsRouteRouteWithChildren
  '/$orgSlug/files': typeof OrgSlugFilesRoute
  '/$orgSlug/onboarding': typeof OrgSlugOnboardingRoute
  '/changelog/$slug': typeof ChangelogSlugRoute
  '/$orgSlug': typeof OrgSlugIndexRoute
  '/changelog': typeof ChangelogIndexRoute
  '/$orgSlug/receipts/$receiptId': typeof OrgSlugReceiptsReceiptIdRoute
  '/$orgSlug/settings/audit': typeof OrgSlugSettingsAuditRoute
  '/$orgSlug/settings/banks': typeof OrgSlugSettingsBanksRoute
  '/$orgSlug/settings/members': typeof OrgSlugSettingsMembersRoute
  '/$orgSlug/settings/organization': typeof OrgSlugSettingsOrganizationRoute
  '/$orgSlug/settings': typeof OrgSlugSettingsIndexRoute
  '/$orgSlug/parties/$partyId/ledger': typeof OrgSlugPartiesPartyIdLedgerRoute
  '/$orgSlug/parties/$partyId/receipts': typeof OrgSlugPartiesPartyIdReceiptsRoute
  '/$orgSlug/parties/$partyId': typeof OrgSlugPartiesPartyIdIndexRoute
  '/api/$orgSlug/receipts/$receiptId/pdf': typeof ApiOrgSlugReceiptsReceiptIdPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/billing': typeof BillingRoute
  '/contact': typeof ContactRoute
  '/create': typeof CreateRoute
  '/customers': typeof CustomersRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$orgSlug/parties': typeof OrgSlugPartiesRouteRoute
  '/$orgSlug/receipts': typeof OrgSlugReceiptsRouteRouteWithChildren
  '/$orgSlug/settings': typeof OrgSlugSettingsRouteRouteWithChildren
  '/$orgSlug/files': typeof OrgSlugFilesRoute
  '/$orgSlug/onboarding': typeof OrgSlugOnboardingRoute
  '/changelog/$slug': typeof ChangelogSlugRoute
  '/$orgSlug/': typeof OrgSlugIndexRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/$orgSlug/parties_/$partyId': typeof OrgSlugPartiesPartyIdRouteWithChildren
  '/$orgSlug/receipts/$receiptId': typeof OrgSlugReceiptsReceiptIdRoute
  '/$orgSlug/settings/audit': typeof OrgSlugSettingsAuditRoute
  '/$orgSlug/settings/banks': typeof OrgSlugSettingsBanksRoute
  '/$orgSlug/settings/members': typeof OrgSlugSettingsMembersRoute
  '/$orgSlug/settings/organization': typeof OrgSlugSettingsOrganizationRoute
  '/$orgSlug/settings/': typeof OrgSlugSettingsIndexRoute
  '/$orgSlug/parties_/$partyId/ledger': typeof OrgSlugPartiesPartyIdLedgerRoute
  '/$orgSlug/parties_/$partyId/receipts': typeof OrgSlugPartiesPartyIdReceiptsRoute
  '/$orgSlug/parties_/$partyId/': typeof OrgSlugPartiesPartyIdIndexRoute
  '/api/$orgSlug/receipts/$receiptId/pdf': typeof ApiOrgSlugReceiptsReceiptIdPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$orgSlug'
    | '/about'
    | '/billing'
    | '/contact'
    | '/create'
    | '/customers'
    | '/join'
    | '/login'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$orgSlug/parties'
    | '/$orgSlug/receipts'
    | '/$orgSlug/settings'
    | '/$orgSlug/files'
    | '/$orgSlug/onboarding'
    | '/changelog/$slug'
    | '/$orgSlug/'
    | '/changelog/'
    | '/$orgSlug/parties/$partyId'
    | '/$orgSlug/receipts/$receiptId'
    | '/$orgSlug/settings/audit'
    | '/$orgSlug/settings/banks'
    | '/$orgSlug/settings/members'
    | '/$orgSlug/settings/organization'
    | '/$orgSlug/settings/'
    | '/$orgSlug/parties/$partyId/ledger'
    | '/$orgSlug/parties/$partyId/receipts'
    | '/$orgSlug/parties/$partyId/'
    | '/api/$orgSlug/receipts/$receiptId/pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/billing'
    | '/contact'
    | '/create'
    | '/customers'
    | '/join'
    | '/login'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$orgSlug/parties'
    | '/$orgSlug/receipts'
    | '/$orgSlug/files'
    | '/$orgSlug/onboarding'
    | '/changelog/$slug'
    | '/$orgSlug'
    | '/changelog'
    | '/$orgSlug/receipts/$receiptId'
    | '/$orgSlug/settings/audit'
    | '/$orgSlug/settings/banks'
    | '/$orgSlug/settings/members'
    | '/$orgSlug/settings/organization'
    | '/$orgSlug/settings'
    | '/$orgSlug/parties/$partyId/ledger'
    | '/$orgSlug/parties/$partyId/receipts'
    | '/$orgSlug/parties/$partyId'
    | '/api/$orgSlug/receipts/$receiptId/pdf'
  id:
    | '__root__'
    | '/'
    | '/$orgSlug'
    | '/about'
    | '/billing'
    | '/contact'
    | '/create'
    | '/customers'
    | '/join'
    | '/login'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$orgSlug/parties'
    | '/$orgSlug/receipts'
    | '/$orgSlug/settings'
    | '/$orgSlug/files'
    | '/$orgSlug/onboarding'
    | '/changelog/$slug'
    | '/$orgSlug/'
    | '/changelog/'
    | '/$orgSlug/parties_/$partyId'
    | '/$orgSlug/receipts/$receiptId'
    | '/$orgSlug/settings/audit'
    | '/$orgSlug/settings/banks'
    | '/$orgSlug/settings/members'
    | '/$orgSlug/settings/organization'
    | '/$orgSlug/settings/'
    | '/$orgSlug/parties_/$partyId/ledger'
    | '/$orgSlug/parties_/$partyId/receipts'
    | '/$orgSlug/parties_/$partyId/'
    | '/api/$orgSlug/receipts/$receiptId/pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrgSlugRouteRoute: typeof OrgSlugRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  BillingRoute: typeof BillingRoute
  ContactRoute: typeof ContactRoute
  CreateRoute: typeof CreateRoute
  CustomersRoute: typeof CustomersRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ChangelogSlugRoute: typeof ChangelogSlugRoute
  ChangelogIndexRoute: typeof ChangelogIndexRoute
  ApiOrgSlugReceiptsReceiptIdPdfRoute: typeof ApiOrgSlugReceiptsReceiptIdPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug': {
      id: '/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof OrgSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/': {
      id: '/$orgSlug/'
      path: '/'
      fullPath: '/$orgSlug/'
      preLoaderRoute: typeof OrgSlugIndexRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/files': {
      id: '/$orgSlug/files'
      path: '/files'
      fullPath: '/$orgSlug/files'
      preLoaderRoute: typeof OrgSlugFilesRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/onboarding': {
      id: '/$orgSlug/onboarding'
      path: '/onboarding'
      fullPath: '/$orgSlug/onboarding'
      preLoaderRoute: typeof OrgSlugOnboardingRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/parties': {
      id: '/$orgSlug/parties'
      path: '/parties'
      fullPath: '/$orgSlug/parties'
      preLoaderRoute: typeof OrgSlugPartiesRouteRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/receipts': {
      id: '/$orgSlug/receipts'
      path: '/receipts'
      fullPath: '/$orgSlug/receipts'
      preLoaderRoute: typeof OrgSlugReceiptsRouteRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/settings': {
      id: '/$orgSlug/settings'
      path: '/settings'
      fullPath: '/$orgSlug/settings'
      preLoaderRoute: typeof OrgSlugSettingsRouteRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/changelog/': {
      id: '/changelog/'
      path: '/changelog'
      fullPath: '/changelog/'
      preLoaderRoute: typeof ChangelogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog/$slug': {
      id: '/changelog/$slug'
      path: '/changelog/$slug'
      fullPath: '/changelog/$slug'
      preLoaderRoute: typeof ChangelogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/parties_/$partyId': {
      id: '/$orgSlug/parties_/$partyId'
      path: '/parties/$partyId'
      fullPath: '/$orgSlug/parties/$partyId'
      preLoaderRoute: typeof OrgSlugPartiesPartyIdRouteImport
      parentRoute: typeof OrgSlugRouteRoute
    }
    '/$orgSlug/receipts/$receiptId': {
      id: '/$orgSlug/receipts/$receiptId'
      path: '/$receiptId'
      fullPath: '/$orgSlug/receipts/$receiptId'
      preLoaderRoute: typeof OrgSlugReceiptsReceiptIdRouteImport
      parentRoute: typeof OrgSlugReceiptsRouteRoute
    }
    '/$orgSlug/settings/': {
      id: '/$orgSlug/settings/'
      path: '/'
      fullPath: '/$orgSlug/settings/'
      preLoaderRoute: typeof OrgSlugSettingsIndexRouteImport
      parentRoute: typeof OrgSlugSettingsRouteRoute
    }
    '/$orgSlug/settings/audit': {
      id: '/$orgSlug/settings/audit'
      path: '/audit'
      fullPath: '/$orgSlug/settings/audit'
      preLoaderRoute: typeof OrgSlugSettingsAuditRouteImport
      parentRoute: typeof OrgSlugSettingsRouteRoute
    }
    '/$orgSlug/settings/banks': {
      id: '/$orgSlug/settings/banks'
      path: '/banks'
      fullPath: '/$orgSlug/settings/banks'
      preLoaderRoute: typeof OrgSlugSettingsBanksRouteImport
      parentRoute: typeof OrgSlugSettingsRouteRoute
    }
    '/$orgSlug/settings/members': {
      id: '/$orgSlug/settings/members'
      path: '/members'
      fullPath: '/$orgSlug/settings/members'
      preLoaderRoute: typeof OrgSlugSettingsMembersRouteImport
      parentRoute: typeof OrgSlugSettingsRouteRoute
    }
    '/$orgSlug/settings/organization': {
      id: '/$orgSlug/settings/organization'
      path: '/organization'
      fullPath: '/$orgSlug/settings/organization'
      preLoaderRoute: typeof OrgSlugSettingsOrganizationRouteImport
      parentRoute: typeof OrgSlugSettingsRouteRoute
    }
    '/$orgSlug/parties_/$partyId/': {
      id: '/$orgSlug/parties_/$partyId/'
      path: '/'
      fullPath: '/$orgSlug/parties/$partyId/'
      preLoaderRoute: typeof OrgSlugPartiesPartyIdIndexRouteImport
      parentRoute: typeof OrgSlugPartiesPartyIdRoute
    }
    '/$orgSlug/parties_/$partyId/ledger': {
      id: '/$orgSlug/parties_/$partyId/ledger'
      path: '/ledger'
      fullPath: '/$orgSlug/parties/$partyId/ledger'
      preLoaderRoute: typeof OrgSlugPartiesPartyIdLedgerRouteImport
      parentRoute: typeof OrgSlugPartiesPartyIdRoute
    }
    '/$orgSlug/parties_/$partyId/receipts': {
      id: '/$orgSlug/parties_/$partyId/receipts'
      path: '/receipts'
      fullPath: '/$orgSlug/parties/$partyId/receipts'
      preLoaderRoute: typeof OrgSlugPartiesPartyIdReceiptsRouteImport
      parentRoute: typeof OrgSlugPartiesPartyIdRoute
    }
    '/api/$orgSlug/receipts/$receiptId/pdf': {
      id: '/api/$orgSlug/receipts/$receiptId/pdf'
      path: '/api/$orgSlug/receipts/$receiptId/pdf'
      fullPath: '/api/$orgSlug/receipts/$receiptId/pdf'
      preLoaderRoute: typeof ApiOrgSlugReceiptsReceiptIdPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OrgSlugReceiptsRouteRouteChildren {
  OrgSlugReceiptsReceiptIdRoute: typeof OrgSlugReceiptsReceiptIdRoute
}

const OrgSlugReceiptsRouteRouteChildren: OrgSlugReceiptsRouteRouteChildren = {
  OrgSlugReceiptsReceiptIdRoute: OrgSlugReceiptsReceiptIdRoute,
}

const OrgSlugReceiptsRouteRouteWithChildren =
  OrgSlugReceiptsRouteRoute._addFileChildren(OrgSlugReceiptsRouteRouteChildren)

interface OrgSlugSettingsRouteRouteChildren {
  OrgSlugSettingsAuditRoute: typeof OrgSlugSettingsAuditRoute
  OrgSlugSettingsBanksRoute: typeof OrgSlugSettingsBanksRoute
  OrgSlugSettingsMembersRoute: typeof OrgSlugSettingsMembersRoute
  OrgSlugSettingsOrganizationRoute: typeof OrgSlugSettingsOrganizationRoute
  OrgSlugSettingsIndexRoute: typeof OrgSlugSettingsIndexRoute
}

const OrgSlugSettingsRouteRouteChildren: OrgSlugSettingsRouteRouteChildren = {
  OrgSlugSettingsAuditRoute: OrgSlugSettingsAuditRoute,
  OrgSlugSettingsBanksRoute: OrgSlugSettingsBanksRoute,
  OrgSlugSettingsMembersRoute: OrgSlugSettingsMembersRoute,
  OrgSlugSettingsOrganizationRoute: OrgSlugSettingsOrganizationRoute,
  OrgSlugSettingsIndexRoute: OrgSlugSettingsIndexRoute,
}

const OrgSlugSettingsRouteRouteWithChildren =
  OrgSlugSettingsRouteRoute._addFileChildren(OrgSlugSettingsRouteRouteChildren)

interface OrgSlugPartiesPartyIdRouteChildren {
  OrgSlugPartiesPartyIdLedgerRoute: typeof OrgSlugPartiesPartyIdLedgerRoute
  OrgSlugPartiesPartyIdReceiptsRoute: typeof OrgSlugPartiesPartyIdReceiptsRoute
  OrgSlugPartiesPartyIdIndexRoute: typeof OrgSlugPartiesPartyIdIndexRoute
}

const OrgSlugPartiesPartyIdRouteChildren: OrgSlugPartiesPartyIdRouteChildren = {
  OrgSlugPartiesPartyIdLedgerRoute: OrgSlugPartiesPartyIdLedgerRoute,
  OrgSlugPartiesPartyIdReceiptsRoute: OrgSlugPartiesPartyIdReceiptsRoute,
  OrgSlugPartiesPartyIdIndexRoute: OrgSlugPartiesPartyIdIndexRoute,
}

const OrgSlugPartiesPartyIdRouteWithChildren =
  OrgSlugPartiesPartyIdRoute._addFileChildren(
    OrgSlugPartiesPartyIdRouteChildren,
  )

interface OrgSlugRouteRouteChildren {
  OrgSlugPartiesRouteRoute: typeof OrgSlugPartiesRouteRoute
  OrgSlugReceiptsRouteRoute: typeof OrgSlugReceiptsRouteRouteWithChildren
  OrgSlugSettingsRouteRoute: typeof OrgSlugSettingsRouteRouteWithChildren
  OrgSlugFilesRoute: typeof OrgSlugFilesRoute
  OrgSlugOnboardingRoute: typeof OrgSlugOnboardingRoute
  OrgSlugIndexRoute: typeof OrgSlugIndexRoute
  OrgSlugPartiesPartyIdRoute: typeof OrgSlugPartiesPartyIdRouteWithChildren
}

const OrgSlugRouteRouteChildren: OrgSlugRouteRouteChildren = {
  OrgSlugPartiesRouteRoute: OrgSlugPartiesRouteRoute,
  OrgSlugReceiptsRouteRoute: OrgSlugReceiptsRouteRouteWithChildren,
  OrgSlugSettingsRouteRoute: OrgSlugSettingsRouteRouteWithChildren,
  OrgSlugFilesRoute: OrgSlugFilesRoute,
  OrgSlugOnboardingRoute: OrgSlugOnboardingRoute,
  OrgSlugIndexRoute: OrgSlugIndexRoute,
  OrgSlugPartiesPartyIdRoute: OrgSlugPartiesPartyIdRouteWithChildren,
}

const OrgSlugRouteRouteWithChildren = OrgSlugRouteRoute._addFileChildren(
  OrgSlugRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrgSlugRouteRoute: OrgSlugRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  BillingRoute: BillingRoute,
  ContactRoute: ContactRoute,
  CreateRoute: CreateRoute,
  CustomersRoute: CustomersRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ChangelogSlugRoute: ChangelogSlugRoute,
  ChangelogIndexRoute: ChangelogIndexRoute,
  ApiOrgSlugReceiptsReceiptIdPdfRoute: ApiOrgSlugReceiptsReceiptIdPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
